// @ts-nocheck
// GENERATED by scripts/gen-embed.ts — do not edit.

import m0 from "../migrations/0001_init.sql" with { type: "text" };
import m1 from "../migrations/0002_workspace_folder_path.sql" with { type: "text" };
import m2 from "../migrations/0003_drop_worker_inbound_fields.sql" with { type: "text" };
import m3 from "../migrations/0004_events_client_seq.sql" with { type: "text" };
import m4 from "../migrations/0005_workers_reachable_addr.sql" with { type: "text" };
import m5 from "../migrations/0006_app_settings.sql" with { type: "text" };
import m6 from "../migrations/0007_sessions_custom_title.sql" with { type: "text" };
import m7 from "../migrations/0008_sessions_git_branch.sql" with { type: "text" };
import m8 from "../migrations/0009_sessions_git_remote.sql" with { type: "text" };
import m9 from "../migrations/0010_sessions_pr_status.sql" with { type: "text" };
import m10 from "../migrations/0011_sessions_ports.sql" with { type: "text" };
import m11 from "../migrations/0012_workers_keeper_stale.sql" with { type: "text" };
import m12 from "../migrations/0013_sessions_spawn_cwd.sql" with { type: "text" };
import m13 from "../migrations/0014_push_subscriptions.sql" with { type: "text" };
import m14 from "../migrations/0015_normalize_legacy_session_kinds.sql" with { type: "text" };
import m15 from "../migrations/0016_agent_entries.sql" with { type: "text" };

export const MIGRATIONS: { name: string; sql: string }[] = [
  { name: "0001_init", sql: m0 },
  { name: "0002_workspace_folder_path", sql: m1 },
  { name: "0003_drop_worker_inbound_fields", sql: m2 },
  { name: "0004_events_client_seq", sql: m3 },
  { name: "0005_workers_reachable_addr", sql: m4 },
  { name: "0006_app_settings", sql: m5 },
  { name: "0007_sessions_custom_title", sql: m6 },
  { name: "0008_sessions_git_branch", sql: m7 },
  { name: "0009_sessions_git_remote", sql: m8 },
  { name: "0010_sessions_pr_status", sql: m9 },
  { name: "0011_sessions_ports", sql: m10 },
  { name: "0012_workers_keeper_stale", sql: m11 },
  { name: "0013_sessions_spawn_cwd", sql: m12 },
  { name: "0014_push_subscriptions", sql: m13 },
  { name: "0015_normalize_legacy_session_kinds", sql: m14 },
  { name: "0016_agent_entries", sql: m15 },
];
