// @ts-nocheck
// GENERATED by scripts/gen-embed.ts — do not edit.

import w0 from "../../web/dist/apple-touch-icon.png" with { type: "file" };
import w1 from "../../web/dist/assets/BrowsePage-T33RGEcZ.js" with { type: "file" };
import w2 from "../../web/dist/assets/CommandPaletteBody-7LOWRNJd.js" with { type: "file" };
import w3 from "../../web/dist/assets/DesignGallery-ByNDdZbe.js" with { type: "file" };
import w4 from "../../web/dist/assets/EmptyState-BsorvLmy.js" with { type: "file" };
import w5 from "../../web/dist/assets/FileViewerSheet-Ozl6J-xz.js" with { type: "file" };
import w6 from "../../web/dist/assets/Help-CF7hAftW.js" with { type: "file" };
import w7 from "../../web/dist/assets/HelpOverlay-B4oG4aT-.js" with { type: "file" };
import w8 from "../../web/dist/assets/Onboarding--zcvPsr7.js" with { type: "file" };
import w9 from "../../web/dist/assets/SettingsRoot-CVFRx9U_.js" with { type: "file" };
import w10 from "../../web/dist/assets/SettingsRoot-Cj-twIHE.css" with { type: "file" };
import w11 from "../../web/dist/assets/index-B4AqCOOZ.js" with { type: "file" };
import w12 from "../../web/dist/assets/index-Bk0hyYQ0.css" with { type: "file" };
import w13 from "../../web/dist/assets/lastWorkspace-Bwq2lPxY.js" with { type: "file" };
import w14 from "../../web/dist/assets/redeemPairToken-BMfO-wts.js" with { type: "file" };
import w15 from "../../web/dist/assets/smoke-B-DOZGgX.js" with { type: "file" };
import w16 from "../../web/dist/assets/smokeHarness-C_i86aZK.js" with { type: "file" };
import w17 from "../../web/dist/assets/vendor-CIQiDVcC.js" with { type: "file" };
import w18 from "../../web/dist/fonts/JetBrainsMonoNerdFontMono-Bold.woff2" with { type: "file" };
import w19 from "../../web/dist/fonts/JetBrainsMonoNerdFontMono-Regular.woff2" with { type: "file" };
import w20 from "../../web/dist/fonts/MaterialSymbolsRounded.woff2" with { type: "file" };
import w21 from "../../web/dist/fonts/RobotoFlex.woff2" with { type: "file" };
import w22 from "../../web/dist/icon-192.png" with { type: "file" };
import w23 from "../../web/dist/icon-32.png" with { type: "file" };
import w24 from "../../web/dist/icon-512.png" with { type: "file" };
import w25 from "../../web/dist/icon-maskable-512.png" with { type: "file" };
import w26 from "../../web/dist/icon-maskable.svg" with { type: "file" };
import w27 from "../../web/dist/icon.svg" with { type: "file" };
import w28 from "../../web/dist/index.html" with { type: "file" };
import w29 from "../../web/dist/manifest.webmanifest" with { type: "file" };
import w30 from "../../web/dist/sw-push.js" with { type: "file" };
import w31 from "../../web/dist/whatsnew.json" with { type: "file" };
import w32 from "../../web/dist/wterm-roost.wasm" with { type: "file" };

export const WEB_ASSETS: Map<string, string> = new Map([
  ["apple-touch-icon.png", w0],
  ["assets/BrowsePage-T33RGEcZ.js", w1],
  ["assets/CommandPaletteBody-7LOWRNJd.js", w2],
  ["assets/DesignGallery-ByNDdZbe.js", w3],
  ["assets/EmptyState-BsorvLmy.js", w4],
  ["assets/FileViewerSheet-Ozl6J-xz.js", w5],
  ["assets/Help-CF7hAftW.js", w6],
  ["assets/HelpOverlay-B4oG4aT-.js", w7],
  ["assets/Onboarding--zcvPsr7.js", w8],
  ["assets/SettingsRoot-CVFRx9U_.js", w9],
  ["assets/SettingsRoot-Cj-twIHE.css", w10],
  ["assets/index-B4AqCOOZ.js", w11],
  ["assets/index-Bk0hyYQ0.css", w12],
  ["assets/lastWorkspace-Bwq2lPxY.js", w13],
  ["assets/redeemPairToken-BMfO-wts.js", w14],
  ["assets/smoke-B-DOZGgX.js", w15],
  ["assets/smokeHarness-C_i86aZK.js", w16],
  ["assets/vendor-CIQiDVcC.js", w17],
  ["fonts/JetBrainsMonoNerdFontMono-Bold.woff2", w18],
  ["fonts/JetBrainsMonoNerdFontMono-Regular.woff2", w19],
  ["fonts/MaterialSymbolsRounded.woff2", w20],
  ["fonts/RobotoFlex.woff2", w21],
  ["icon-192.png", w22],
  ["icon-32.png", w23],
  ["icon-512.png", w24],
  ["icon-maskable-512.png", w25],
  ["icon-maskable.svg", w26],
  ["icon.svg", w27],
  ["index.html", w28],
  ["manifest.webmanifest", w29],
  ["sw-push.js", w30],
  ["whatsnew.json", w31],
  ["wterm-roost.wasm", w32],
]);
