// @ts-nocheck
// GENERATED by scripts/gen-embed.ts — do not edit.

import w0 from "../../web/dist/apple-touch-icon.png" with { type: "file" };
import w1 from "../../web/dist/assets/BrowsePage-BZCw72Et.js" with { type: "file" };
import w2 from "../../web/dist/assets/CommandPaletteBody-GxNsKg48.js" with { type: "file" };
import w3 from "../../web/dist/assets/DesignGallery-Cw2Taodg.js" with { type: "file" };
import w4 from "../../web/dist/assets/EmptyState-DNc6lQdy.js" with { type: "file" };
import w5 from "../../web/dist/assets/FileViewerSheet-CbMudW3G.js" with { type: "file" };
import w6 from "../../web/dist/assets/Help-sybZxnyy.js" with { type: "file" };
import w7 from "../../web/dist/assets/HelpOverlay-C_P-4wjQ.js" with { type: "file" };
import w8 from "../../web/dist/assets/Onboarding-DOXswwwH.js" with { type: "file" };
import w9 from "../../web/dist/assets/SettingsRoot-Cj-twIHE.css" with { type: "file" };
import w10 from "../../web/dist/assets/SettingsRoot-D0iWP82T.js" with { type: "file" };
import w11 from "../../web/dist/assets/StatusDot-CxZzYggj.js" with { type: "file" };
import w12 from "../../web/dist/assets/index-BjuVAq1u.js" with { type: "file" };
import w13 from "../../web/dist/assets/index-phCZgy-9.css" with { type: "file" };
import w14 from "../../web/dist/assets/lastWorkspace-Bwq2lPxY.js" with { type: "file" };
import w15 from "../../web/dist/assets/redeemPairToken-S8QBIcBz.js" with { type: "file" };
import w16 from "../../web/dist/assets/smoke-BTeb-V5b.js" with { type: "file" };
import w17 from "../../web/dist/assets/smokeHarness-C_i86aZK.js" with { type: "file" };
import w18 from "../../web/dist/assets/vendor-ReV1kwbQ.js" with { type: "file" };
import w19 from "../../web/dist/fonts/JetBrainsMonoNerdFontMono-Bold.woff2" with { type: "file" };
import w20 from "../../web/dist/fonts/JetBrainsMonoNerdFontMono-Regular.woff2" with { type: "file" };
import w21 from "../../web/dist/fonts/MaterialSymbolsRounded.woff2" with { type: "file" };
import w22 from "../../web/dist/fonts/RobotoFlex.woff2" with { type: "file" };
import w23 from "../../web/dist/icon-192.png" with { type: "file" };
import w24 from "../../web/dist/icon-32.png" with { type: "file" };
import w25 from "../../web/dist/icon-512.png" with { type: "file" };
import w26 from "../../web/dist/icon-maskable-512.png" with { type: "file" };
import w27 from "../../web/dist/icon-maskable.svg" with { type: "file" };
import w28 from "../../web/dist/icon.svg" with { type: "file" };
import w29 from "../../web/dist/index.html" with { type: "file" };
import w30 from "../../web/dist/manifest.webmanifest" with { type: "file" };
import w31 from "../../web/dist/sw-push.js" with { type: "file" };
import w32 from "../../web/dist/whatsnew.json" with { type: "file" };
import w33 from "../../web/dist/wterm-roost.wasm" with { type: "file" };

export const WEB_ASSETS: Map<string, string> = new Map([
  ["apple-touch-icon.png", w0],
  ["assets/BrowsePage-BZCw72Et.js", w1],
  ["assets/CommandPaletteBody-GxNsKg48.js", w2],
  ["assets/DesignGallery-Cw2Taodg.js", w3],
  ["assets/EmptyState-DNc6lQdy.js", w4],
  ["assets/FileViewerSheet-CbMudW3G.js", w5],
  ["assets/Help-sybZxnyy.js", w6],
  ["assets/HelpOverlay-C_P-4wjQ.js", w7],
  ["assets/Onboarding-DOXswwwH.js", w8],
  ["assets/SettingsRoot-Cj-twIHE.css", w9],
  ["assets/SettingsRoot-D0iWP82T.js", w10],
  ["assets/StatusDot-CxZzYggj.js", w11],
  ["assets/index-BjuVAq1u.js", w12],
  ["assets/index-phCZgy-9.css", w13],
  ["assets/lastWorkspace-Bwq2lPxY.js", w14],
  ["assets/redeemPairToken-S8QBIcBz.js", w15],
  ["assets/smoke-BTeb-V5b.js", w16],
  ["assets/smokeHarness-C_i86aZK.js", w17],
  ["assets/vendor-ReV1kwbQ.js", w18],
  ["fonts/JetBrainsMonoNerdFontMono-Bold.woff2", w19],
  ["fonts/JetBrainsMonoNerdFontMono-Regular.woff2", w20],
  ["fonts/MaterialSymbolsRounded.woff2", w21],
  ["fonts/RobotoFlex.woff2", w22],
  ["icon-192.png", w23],
  ["icon-32.png", w24],
  ["icon-512.png", w25],
  ["icon-maskable-512.png", w26],
  ["icon-maskable.svg", w27],
  ["icon.svg", w28],
  ["index.html", w29],
  ["manifest.webmanifest", w30],
  ["sw-push.js", w31],
  ["whatsnew.json", w32],
  ["wterm-roost.wasm", w33],
]);
