// @ts-nocheck
// GENERATED by scripts/gen-embed.ts — do not edit.
// Empty stub: from-source worker reads integration assets from disk.
export const OMP_AGENT_INTEGRATION = "";
export const PI_AGENT_INTEGRATION = "";
