// @ts-nocheck
// GENERATED by scripts/gen-embed.ts — do not edit.
// Empty stub: from-source worker reads integration assets from disk.
import type { EmbeddedAgentIntegrationAsset } from "./integration-assets.ts";
export const AGENT_INTEGRATION_ASSETS: readonly EmbeddedAgentIntegrationAsset[] = [];
