//! The coordinator's Web Push identity: a P-256 keypair that lives in the
//! `dashboard_id IS NULL` scope of `app_settings` and is read and written
//! nowhere else.
//!
//! Owned by the push domain. `PushGetConfig` and the sender share one store, so
//! first-use generation is decided once per process rather than once per call.
//!
//! WHY THE SCOPE IS WRITTEN IN EVERY STATEMENT. `app_settings`' primary key is
//! `(dashboard_id, key)` and `dashboard_id` is nullable, so SQLite treats two
//! NULL-scoped rows with the same key as DISTINCT rather than colliding. The
//! `IS NULL` predicate is therefore not decoration on these three statements --
//! it is what keeps the read from finding a tenant row and the insert from
//! colliding with one. A per-dashboard VAPID row would silently shadow the
//! global identity (`vapid.ts:45-47`).
//!
//! WHY FIRST USE IS SERIALISED BY THE DATABASE. v2 held a module-level
//! in-flight promise, which serialises one process and nothing else. A
//! `BEGIN IMMEDIATE` transaction serialises the read-then-generate-then-insert
//! against every writer, so the second first-use observes the committed row
//! instead of minting a second identity. It is the same guarantee with a wider
//! scope, and it needs no promise to hold.

use std::sync::{Arc, Mutex};

use serde::{Deserialize, Serialize};
use sqlx::{Row, SqlitePool};

use crate::db::CoordDb;

/// The `app_settings` key the identity is stored under.
///
/// `push.vapid` (`vapid.ts:9`). The prefix is there so a future setting beside
/// it cannot collide, and so an operator reading the table can tell what the
/// row is without decoding it.
pub const VAPID_SETTING_KEY: &str = "push.vapid";

/// The width of a P-256 private scalar.
const PRIVATE_KEY_BYTES: usize = 32;

/// Why the VAPID identity could not be loaded, generated, or persisted.
#[derive(Debug, thiserror::Error)]
pub enum VapidError {
    /// The stored row is not a keypair. Refusing beats sending with a key the
    /// operator cannot rotate, and the row is regenerated by hand after the
    /// operator has looked at it.
    #[error("stored VAPID keypair is invalid")]
    StoredKeysInvalid,
    /// No usable entropy, or no valid P-256 scalar came out of it.
    #[error("VAPID key generation failed: {0}")]
    GenerationFailed(String),
    /// The coordinator-global row could not be read or written.
    #[error("vapid store: {0}")]
    Store(sqlx::Error),
}

/// A VAPID keypair, both halves unpadded base64url.
///
/// The same shape `web-push`'s `generateVAPIDKeys` returns, so a row written by
/// v2 is readable here and a row written here is readable there: the public
/// half is the uncompressed P-256 point, the private half is the raw scalar.
///
/// THE JSON FIELD NAMES ARE `publicKey` AND `privateKey`, camelCase, and they
/// are a WIRE COMPATIBILITY CONTRACT, not a style choice. v2 stores
/// `JSON.stringify({publicKey, privateKey})` (`vapid.ts:38`), so a row written
/// by v2 must deserialize here. Rust's default would be `public_key` and the
/// row would parse into a struct of two absent fields, which `from_str` reports
/// as a missing field rather than as a shape mismatch -- so the failure would
/// present as "stored VAPID keypair is invalid" on a database that is perfectly
/// fine.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct VapidKeys {
    /// The uncompressed public point, base64url. This is what `PushGetConfig`
    /// hands the browser.
    pub public_key: String,
    /// The private scalar, base64url. Never leaves the coordinator.
    pub private_key: String,
}

/// Mints a keypair. A trait so a test can count generations without changing
/// the store's behaviour; production always uses [`P256KeypairGenerator`].
pub trait VapidKeyGenerator: Send + Sync {
    /// A fresh P-256 keypair, or why none could be produced.
    fn generate(&self) -> Result<VapidKeys, VapidError>;
}

/// The production generator: OS entropy into a P-256 scalar, and `web-push`
/// derives the public half.
///
/// The scalar is validated by `web-push` itself -- `from_base64_no_sub` refuses
/// anything outside `[1, n-1]` -- so this does not carry the curve order, and a
/// rejected draw is simply redrawn. That rejection is roughly one draw in 2^32,
/// so the bound below is a backstop against a broken entropy source rather than
/// a budget.
///
/// The entropy source is the kernel CSPRNG at `/dev/urandom`. v3 supports Linux
/// and macOS only (`CLAUDE.md` "Fixed decisions": Windows is paused), and both
/// ship that device, so there is no platform branch to get wrong. The
/// `getrandom` crate would be the tidier spelling; it is not reachable from
/// this crate's declared dependencies today, and this is the one place a
/// hand-rolled spelling was accepted rather than left unimplemented.
#[derive(Debug, Clone, Copy, Default)]
pub struct P256KeypairGenerator;

/// Draws are bounded so a broken entropy source fails loudly instead of
/// spinning.
const MAX_DRAWS: usize = 8;

impl VapidKeyGenerator for P256KeypairGenerator {
    fn generate(&self) -> Result<VapidKeys, VapidError> {
        for _ in 0..MAX_DRAWS {
            let scalar = crate::coord_core::ids::draw::<PRIVATE_KEY_BYTES>()
                .map_err(|error| VapidError::GenerationFailed(error.to_string()))?;
            let private_key = roost_host::b64url_encode(&scalar);
            let Ok(builder) = web_push::VapidSignatureBuilder::from_base64_no_sub(&private_key)
            else {
                continue;
            };
            return Ok(VapidKeys {
                public_key: roost_host::b64url_encode(&builder.get_public_key()),
                private_key,
            });
        }
        Err(VapidError::GenerationFailed(
            "no valid P-256 scalar in eight draws".to_owned(),
        ))
    }
}

/// The coordinator's VAPID identity: one cached keypair over one database.
///
/// A value, never a crate global. `services.rs` forbids global mutable state
/// and the reason is visible in v2's own test surface: two coordinators, or
/// two tests over two temporary databases, must not share one identity.
#[derive(Clone)]
pub struct VapidKeyStore {
    generator: Arc<dyn VapidKeyGenerator>,
    cached: Arc<Mutex<Option<VapidKeys>>>,
}

impl std::fmt::Debug for VapidKeyStore {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let loaded = self
            .cached
            .lock()
            .map(|cached| cached.is_some())
            .unwrap_or(false);
        formatter
            .debug_struct("VapidKeyStore")
            .field("loaded", &loaded)
            .finish_non_exhaustive()
    }
}

impl VapidKeyStore {
    /// A store that mints its identity with `generator`.
    #[must_use]
    pub fn new(generator: Arc<dyn VapidKeyGenerator>) -> Self {
        Self {
            generator,
            cached: Arc::new(Mutex::new(None)),
        }
    }

    /// The stored keypair, generating and persisting one on first use.
    ///
    /// The cache is a `std::sync::Mutex` because every critical section here is
    /// synchronous: the await happens while no guard is held, so nothing is
    /// held across one.
    pub async fn keys(&self, database: &CoordDb) -> Result<VapidKeys, VapidError> {
        if let Some(keys) = self.cached() {
            return Ok(keys);
        }
        let loaded = load_or_create(database.pool(), self.generator.as_ref()).await?;
        *self.cached.lock().map_err(|_| poisoned("cache"))? = Some(loaded.clone());
        Ok(loaded)
    }

    /// Forget the cached identity, so the next read reloads from the row.
    ///
    /// The seam for a test over a second database and for an operator-driven
    /// rotation; there is no automatic invalidation, because a keypair does not
    /// change on its own.
    pub fn invalidate(&self) {
        if let Ok(mut cached) = self.cached.lock() {
            *cached = None;
        }
    }

    /// The cached keypair, if one has been loaded.
    fn cached(&self) -> Option<VapidKeys> {
        self.cached.lock().ok().and_then(|cached| cached.clone())
    }
}

fn poisoned(what: &str) -> VapidError {
    VapidError::GenerationFailed(format!("{what} lock poisoned"))
}

/// Read the coordinator-global row, or create it, inside one write
/// transaction.
///
/// `BEGIN IMMEDIATE` takes the write lock up front, which is what makes the
/// read and the insert one decision: a second first-use blocks here, then
/// observes the row the first one committed and returns it, rather than minting
/// a second identity. The read-back after the insert is deliberate and is not
/// dead code -- it is the assertion that the row that landed is the
/// coordinator-global one, and it is what makes a row written by another
/// writer the answer rather than a duplicate.
async fn load_or_create(
    pool: &SqlitePool,
    generator: &dyn VapidKeyGenerator,
) -> Result<VapidKeys, VapidError> {
    let mut transaction = pool
        .begin_with("BEGIN IMMEDIATE")
        .await
        .map_err(VapidError::Store)?;
    if let Some(stored) = read_row(&mut transaction).await? {
        transaction.commit().await.map_err(VapidError::Store)?;
        return Ok(stored);
    }
    let generated = generator.generate()?;
    sqlx::query(
        "INSERT INTO app_settings (dashboard_id, key, value, updated_at_ms) \
         VALUES (NULL, ?, ?, ?)",
    )
    .bind(VAPID_SETTING_KEY)
    .bind(
        serde_json::to_string(&generated)
            .map_err(|error| VapidError::GenerationFailed(error.to_string()))?,
    )
    .bind(crate::rpc::service::now_ms())
    .execute(&mut *transaction)
    .await
    .map_err(VapidError::Store)?;
    let stored = read_row(&mut transaction)
        .await?
        .ok_or(VapidError::StoredKeysInvalid)?;
    transaction.commit().await.map_err(VapidError::Store)?;
    Ok(stored)
}

/// The NULL-scoped `push.vapid` row, parsed.
async fn read_row(
    transaction: &mut sqlx::Transaction<'_, sqlx::Sqlite>,
) -> Result<Option<VapidKeys>, VapidError> {
    let row = sqlx::query(
        "SELECT value FROM app_settings \
         WHERE dashboard_id IS NULL AND key = ?",
    )
    .bind(VAPID_SETTING_KEY)
    .fetch_optional(&mut **transaction)
    .await
    .map_err(VapidError::Store)?;
    row.map(|row| {
        let value: String = row.try_get("value").map_err(VapidError::Store)?;
        serde_json::from_str(&value).map_err(|_| VapidError::StoredKeysInvalid)
    })
    .transpose()
}

#[cfg(test)]
mod tests {
    use super::{P256KeypairGenerator, VAPID_SETTING_KEY, VapidKeyGenerator};

    #[test]
    fn a_generated_keypair_is_base64url_and_the_public_half_is_an_uncompressed_point() {
        let keys = P256KeypairGenerator.generate().expect("a keypair");
        let public = roost_host::b64url_decode(&keys.public_key).expect("base64url");
        let private = roost_host::b64url_decode(&keys.private_key).expect("base64url");
        assert_eq!(public.len(), 65, "an uncompressed P-256 point");
        assert_eq!(public[0], 0x04, "the uncompressed point marker");
        assert_eq!(private.len(), 32, "a P-256 scalar");
        assert_ne!(keys.public_key, keys.private_key);
    }

    #[test]
    fn two_generations_produce_two_identities() {
        let first = P256KeypairGenerator.generate().expect("a keypair");
        let second = P256KeypairGenerator.generate().expect("a keypair");
        assert_ne!(first.private_key, second.private_key);
        assert_ne!(first.public_key, second.public_key);
    }

    #[test]
    fn the_setting_key_is_the_one_v2_wrote() {
        assert_eq!(VAPID_SETTING_KEY, "push.vapid");
    }
}
