// @ts-nocheck
// GENERATED by scripts/gen-embed.ts — do not edit.
// Empty stub: from-source quickstart runs the on-disk install scripts.
export const COORD_INSTALL_SH = "";
export const WORKER_INSTALL_SH = "";
