CC = "crates/roost-client-core/src/"
WD = "crates/roost-web/src/components/deck/"
FOLLOW = CC + "deck/intent/follow.rs"
STATE = CC + "deck/state.rs"
INTENT = CC + "deck/intent.rs"
CLOSE = CC + "deck/intent/close.rs"
SPAWN = CC + "deck/spawn.rs"
BADGE = CC + "deck/tab_badge.rs"
VIEW = CC + "deck/view.rs"
WARM = CC + "deck/warm_set.rs"
CURSOR = CC + "store/sidebar/cursor.rs"
MEM = CC + "store/sidebar/memory.rs"
FG = CC + "store/sidebar/folder_groups.rs"
AP = CC + "store/sidebar/agents_projection.rs"
SPROJ = CC + "client/agents/status_projection.rs"
UI = CC + "store/ui.rs"
SI = CC + "store/sidebar/intent.rs"
FN = CC + "store/folder_name_validation.rs"
GEO = WD + "terminal_deck_geometry.rs"
SW = WD + "deck_swipe.rs"
SWS = WD + "deck_swipe_style.rs"
TOUCH = WD + "deck_swipe_touch.rs"

CC_TESTS = ["deck_intent", "deck_spawn", "deck_tab_badge", "deck_view", "deck_warm_set",
            "store_sidebar", "sidebar_intent", "folder_name_validation"]
WEB_TESTS = ["deck_geometry", "deck_swipe", "deck_swipe_touch"]


def tests(names):
    out = []
    for n in names:
        out += ["--test", n]
    return out


CRATE_CMD = {
    "cc": ["cargo", "test", "-p", "roost-client-core", "--no-fail-fast"] + tests(CC_TESTS),
    "web": ["cargo", "test", "-p", "roost-web", "--no-fail-fast"] + tests(WEB_TESTS),
}


def M(id, file, old, new, change, expect):
    return dict(id=id, file=file, old=old, new=new, change=change,
                expect=expect if isinstance(expect, list) else [expect])


MUT = {
    # ---- deck intent
    "DI1": M("DI1", FOLLOW, "    if !seeded {", "    if !seeded || true {",
             "observe: note_change on every observation, not only the seeding one",
             "observing_seeds_the_folder_once_and_pulls_the_route_into_focus"),
    "DI2": M("DI2", STATE, ".map_or(1, |last| last.sequence + 1);",
             ".map_or(1, |last| if last.path == path { last.sequence } else { last.sequence + 1 });",
             "request_navigation: a repeated path reuses the previous sequence (dedupe)",
             "selecting_a_tab_persists_it_and_navigates_once_per_request"),
    "DI3": M("DI3", FOLLOW, "    if lands_in_spotlit {", "    if lands_in_spotlit && false {",
             "select_session: the spotlight no longer follows a tab swapped inside the floated pane",
             "a_tab_swapped_inside_the_floated_pane_keeps_the_spotlight"),
    "DI4": M("DI4", INTENT,
             "            if !pane_focus_persists(Some(&current), pane_id, *compact)\n                || current.focused_pane_id == *pane_id\n            {",
             "            if !pane_focus_persists(Some(&current), pane_id, *compact)\n            {",
             "FocusPane: drop the already-focused no-op guard (refocus commits again)",
             "focusing_a_pane_navigates_to_its_tab_and_refocusing_is_a_no_op"),
    "DI5": M("DI5", CLOSE, "    if viewed {\n        store.deck.request_navigation(destination);",
             "    if viewed || true {\n        store.deck.request_navigation(destination);",
             "close_session: navigate even when the closed tab was not the viewed one",
             "closing_an_unviewed_tab_does_not_move_the_route_and_the_last_tab_goes_home"),
    "DI6": M("DI6", INTENT, "                next = select_tab(&next, active);",
             "                let _ = active;",
             "Arrange: drop the select_tab that keeps the route session focused",
             "arrange_rebuilds_from_the_live_set_and_keeps_the_route_session_selected"),
    "DI7": M("DI7", FOLLOW, "    if previous.is_some_and(|previous| previous != folder_key) {",
             "    if previous.is_none_or(|previous| previous != folder_key) {",
             "observe: the first observation (no previous folder) counts as a folder change",
             "a_folder_change_drops_the_spotlight_but_the_first_observation_does_not"),
    "DI8": M("DI8", STATE, "        if let Err(error) = self.records.persist(storage) {",
             "        if let Err(error) = Ok::<(), String>(()) {",
             "DeckState::commit: stop persisting the records",
             "split_mints_a_fresh_pane_and_the_arrangement_survives_a_reload"),
    # ---- deck spawn
    "SP1": M("SP1", SPAWN, '            Self::Split { .. } => "Split terminal failed",',
             '            Self::Split { .. } => "New terminal failed",',
             "refused: Split reuses the NewTab prefix",
             "a_refused_split_reports_the_failure_and_commits_no_layout_or_route"),
    "SP2": M("SP2", SPAWN, "                insert_first: false,", "                insert_first: true,",
             "landed: a split inserts the new pane BEFORE the asking pane",
             "an_admitted_split_lands_after_its_pane_and_shows_the_new_terminal"),
    "SP3": M("SP3", INTENT, "                    .filter(|id| *id != session_id)",
             "                    .filter(|_| true)",
             "OpenSpawned: resolve the focus with the new session already folded in",
             "an_admitted_new_tab_focuses_its_pane_and_the_route_pulls_it_in"),
    # ---- tab badge
    "TB1": M("TB1", BADGE, "Some(index) if tab_count > 1 && index < tab_count =>",
             "Some(index) if tab_count > 0 && index < tab_count =>",
             "a lone terminal prints a fraction (count > 0)", "a_lone_terminal_stays_a_bare_number"),
    "TB2": M("TB2", BADGE, "Some(index) if tab_count > 1 && index < tab_count =>",
             "Some(index) if tab_count > 1 && index <= tab_count =>",
             "index bound off-by-one (<=)", "an_index_past_the_end_never_prints_six_of_five"),
    "TB3": M("TB3", BADGE, "            let position = index + 1;", "            let position = index;",
             "0-based position printed",
             ["first_of_two_reads_one_of_two", "last_of_two_reads_two_of_two",
              "last_of_five_reads_five_of_five"]),
    "TB4": M("TB4", BADGE, 'if tab_count == 1 { "" } else { "s" }',
             'if tab_count <= 1 { "" } else { "s" }',
             "zero reads singular", "an_empty_list_reads_zero"),
    "TB5": M("TB5", BADGE, "    match active_index {", "    match active_index.or(Some(0)) {",
             "unknown active terminal treated as the first",
             "an_unknown_active_terminal_falls_back_to_the_total"),
    # ---- deck view
    "V1": M("V1", VIEW, "    if size.w == 0.0 || size.h == 0.0 {\n        return DeckView::default();",
            "    if size.w == 0.0 && size.h == 0.0 {\n        return DeckView::default();",
            "deck_view: paints when only one axis is measured (|| -> &&)",
            "nothing_paints_before_the_deck_is_measured"),
    "V2": M("V2", VIEW,
            "            Some(active) if leaf.tabs.iter().any(|tab| tab == active) => active.to_owned(),",
            "            Some(active) if false && leaf.tabs.iter().any(|tab| tab == active) => active.to_owned(),",
            "deck_view compact: the stored selection wins over the route",
            "a_compact_host_paints_the_followed_sessions_pane_full_bleed"),
    "V3": M("V3", VIEW, "        current.to_mut().root = root;", "        let _ = root;",
            "deck_view: transient drag ratios are not applied",
            "a_divider_mid_drag_paints_at_its_transient_ratio"),
    "V4": M("V4", VIEW, "    let margin_x = (size.w * 0.06).max(24.0);",
            "    let margin_x = size.w * 0.06;",
            "spotlight_rect: no 24px floor on the x margin",
            "the_spotlight_floats_the_selected_tab_over_an_inset_card"),
    "V5": M("V5", VIEW, "(swipe_neighbor_id, compact, view.panes.first())",
            "(swipe_neighbor_id, true, view.panes.first())",
            "slot_by_session: the swipe neighbour is slotted off compact too",
            "the_swipe_neighbour_rides_in_over_the_one_compact_pane"),
    "V6": M("V6", VIEW, "            h: (pane.rect.h - strip_height).max(0.0),",
            "            h: pane.rect.h - strip_height,",
            "park_size_by_session: no zero floor on the parked height",
            "parked_tabs_size_to_their_panes_terminal_area"),
    "V7": M("V7", VIEW, ".filter(|id| warm.contains(id) || slots.contains_key(*id))",
            ".filter(|id| slots.contains_key(*id))",
            "mounted_session_ids: warm sessions are not mounted",
            "only_slotted_or_warm_open_sessions_stay_mounted"),
    "V8": M("V8", VIEW,
            "        .or(if surface_visible {\n            None\n        } else {\n            retained_session_id\n        })",
            "        .or(retained_session_id)",
            "deck_session_id: the retained session shows even with the surface visible",
            "an_overlay_route_keeps_following_the_last_session"),
    "V9": M("V9", VIEW, "    if compact {\n        return None;\n    }",
            "    if compact && false {\n        return None;\n    }",
            "spotlight_pane: a compact host floats",
            "the_spotlight_floats_the_selected_tab_over_an_inset_card"),
    # ---- warm set
    "W1": M("W1", WARM, "            .filter(|id| open_ids.contains(*id) && !slotted.contains(id))",
            "            .filter(|id| !slotted.contains(id))",
            "advance: closed ids are kept warm",
            "a_closed_id_disappears_without_counting_against_the_limit"),
    "W2": M("W2", WARM, "            if open_ids.contains(id) && !slotted.contains(&id) {",
            "            if !slotted.contains(&id) {",
            "advance: a slot naming a non-open session is warmed",
            "a_slot_naming_a_session_that_is_not_open_is_not_warmed"),
    "W3": M("W3", WARM, "        if next == self.ids {\n            return false;\n        }",
            "        if next == self.ids && false {\n            return false;\n        }",
            "advance: always reports a change",
            "the_same_inputs_report_no_change"),
    "W4": M("W4", WARM, "        if next == self.ids {",
            "        if next.len() == self.ids.len() && next.iter().all(|id| self.ids.contains(id)) {",
            "advance: change detection by membership only (reorder ignored)",
            "a_pure_reorder_is_a_change"),
    # ---- sidebar store
    "S1": M("S1", CURSOR, "                None if delta > 0 => Some(0),",
            "                None if delta < 0 => Some(0),",
            "move_cursor: from no highlight, down lands on the last row",
            "moving_from_no_highlight_lands_on_the_first_row_and_clamps_at_the_top"),
    "S2": M("S2", CURSOR, "let last = i64::try_from(len - 1).unwrap_or(i64::MAX);",
            "let last = i64::try_from(len).unwrap_or(i64::MAX);",
            "move_cursor: clamp one past the last row", "moving_clamps_at_the_bottom"),
    "S3": M("S3", MEM, "            storage.set(LAST_SESSION_BY_FOLDER_KEY, &encoded);",
            "            let _ = encoded;",
            "remember_visit: the folder map is not persisted",
            "a_visit_stores_the_restore_path_and_the_folders_last_session"),
    "S4": M("S4", MEM, '    format!("{worker_fp}\\u{0}{folder}")',
            "    let _ = worker_fp;\n    folder.to_owned()",
            "folder_memory_key: the machine is dropped from the key",
            "the_folder_map_keys_by_machine_and_folder_and_the_newest_visit_wins"),
    "S5": M("S5", MEM, '        .filter(|path| !path.is_empty() && path != "/")',
            "        .filter(|path| !path.is_empty())",
            "last_terminal_path: \"/\" reads as a path", "nothing_stored_reads_as_none"),
    "S6": M("S6", FG, '&[group.name.as_str(), &group.server, &group.spawn_cwd].join("\\n"),',
            '&[group.name.as_str(), &group.spawn_cwd].join("\\n"),',
            "filter_folder_groups: the machine label is not searched",
            "the_folder_filter_matches_every_term_across_name_machine_and_path"),
    "S7": M("S7", FG, "            terms.iter().all(|term| text.contains(term))",
            "            terms.iter().any(|term| text.contains(term))",
            "filter_folder_groups: any term matches (all -> any)",
            "an_empty_filter_keeps_order_and_a_missing_term_excludes"),
    "S8": M("S8", SPROJ,
            "                self.arrivals.remove(&session_id);\n                self.statuses.remove(&session_id);",
            "                self.arrivals.remove(&session_id);",
            "apply_update: an inactive (deletion) report leaves the retained status in place",
            "a_removed_status_removes_its_agent_row"),
    "S9": M("S9", AP, "    for document in filter_navigation_search_documents(documents, query) {",
            '    for document in filter_navigation_search_documents(documents, "") {',
            "project_sidebar_agent_groups: the query is ignored",
            "agent_rows_filter_through_the_navigation_metadata"),
    "S10": M("S10", FG,
             "    groups.sort_by(|left, right| right.latest_activity.cmp(&left.latest_activity));",
             "    groups.sort_by(|left, right| left.latest_activity.cmp(&right.latest_activity));",
             "build_folder_groups_from: oldest folder first",
             "one_path_on_two_machines_is_two_groups_in_folder_order"),
    "S11": M("S11", AP, "            Some(store.agent_seen.acknowledged_revision(status)),",
             "            None,",
             "project_sidebar_agent_groups: the seen ledger is not consulted",
             "an_unseen_completion_reads_done_until_acknowledged"),
    # ---- sidebar intent
    "SI1": M("SI1", UI, "    storage.set(SIDEBAR_VIEW_KEY, view.as_str());", "    let _ = storage;",
             "set_sidebar_view: the view is not persisted",
             "the_stored_sidebar_view_is_the_one_a_new_document_shows"),
    "SI2": M("SI2", SI, "        store.ui.sidebar_collapsed && toggle_sidebar_collapsed(store, storage)",
             "        toggle_sidebar_collapsed(store, storage)",
             "reveal_for_search: desktop toggles the rail even when expanded",
             "search_opens_a_closed_drawer_or_expands_a_collapsed_rail_and_nothing_else"),
    "SI3": M("SI3", SI, "            *close_drawer && close_sidebar(store)", "            close_sidebar(store)",
             "RecordNavigation: every row navigation closes the drawer",
             "a_row_navigation_records_recency_the_workspace_and_closes_the_drawer"),
    "SI4": M("SI4", SI, "    if changed && cursor_or_memory {", "    if cursor_or_memory {",
             "apply_sidebar_intent: an unchanged cursor publish still bumps the revision",
             "a_cursor_move_repaints_and_republishing_the_same_rows_does_not"),
    # ---- folder name validation
    "F1": M("F1", FN, "u32::from(character) < 0x20", "u32::from(character) < 0x09",
            "control-character bound lowered below TAB",
            "separators_blank_names_and_control_characters_are_named"),
    "F2": M("F2", FN, "        .any(|sibling| sibling.to_lowercase() == lower)",
            "        .any(|sibling| *sibling == trimmed)",
            "sibling collision compared case-sensitively",
            "a_sibling_collision_ignores_case_and_quotes_the_trimmed_name"),
    "F3": M("F3", FN, '    if trimmed == "." || trimmed == ".." {', '    if trimmed == "." {',
            "the dot rule misses \"..\" (falls to the trailing-period rule)",
            "dot_names_trailing_periods_and_length_are_refused_in_order"),
    # ---- web geometry
    "G1": M("G1", GEO, "park.map_or(if deck.w > 0.0 { deck.w } else { 800.0 }, |park| park.w)",
            "park.map_or(if deck.w > 0.0 { deck.w } else { 800.0 }, |_park| deck.w)",
            "parked slot laid out at the deck width, not its reveal width",
            "a_parked_terminal_stays_laid_out_at_its_reveal_size"),
    "G2": M("G2", GEO, "park.map_or(if deck.w > 0.0 { deck.w } else { 800.0 }, |park| park.w)",
            "park.map_or(deck.w, |park| park.w)",
            "unmeasured fallback width dropped (0px)",
            "an_unparked_terminal_falls_back_to_the_deck_then_a_default_box"),
    "G3": M("G3", GEO, '        .with("top", px(rect.y + strip_height))', '        .with("top", px(rect.y))',
            "slotted terminal paints over its strip",
            "a_slotted_terminal_sits_below_its_strip_and_the_focused_one_on_top"),
    "G4": M("G4", GEO,
            '            .with("top", px(rect.y))\n            .with("width", px(rect.w))\n            .with("height", px(rect.h))',
            '            .with("top", px(rect.y + strip_height))\n            .with("width", px(rect.w))\n            .with("height", px(rect.h))',
            "spotlit card offset by a strip it does not have",
            "the_floated_card_covers_its_whole_rect_above_the_scrim"),
    # ---- web swipe
    "X1": M("X1", SW, "    if SwipeDirection::of_travel(dx) != dir {\n        return false;\n    }",
            "    if SwipeDirection::of_travel(dx) != dir && false {\n        return false;\n    }",
            "should_commit_switch: armed-direction check dropped",
            "should_commit_switch_needs_the_armed_direction_and_distance_or_a_flick"),
    "X2": M("X2", SW, "    if width <= 0.0 {\n        return 0;\n    }",
            "    if width < 0.0 {\n        return 0;\n    }",
            "settle_duration_ms: zero-width guard off by one (<= -> <)",
            "settle_duration_is_constant_speed_per_screen_width"),
    "X3": M("X3", SW,
            "        (false, SwipeDirection::Next) => SwipeMode::NewTerminal,\n        (false, SwipeDirection::Previous) => SwipeMode::Workspace,",
            "        (false, SwipeDirection::Next) => SwipeMode::Workspace,\n        (false, SwipeDirection::Previous) => SwipeMode::NewTerminal,",
            "end_mode: end affordances swapped", "an_end_of_list_swipe_becomes_its_affordance"),
    "X4": M("X4", SW, "    (offset.abs() / (width * SWITCH_DIST_FRAC)).min(1.0)",
            "    offset.abs() / (width * SWITCH_DIST_FRAC)",
            "new_fab_progress: unclamped", "new_fab_progress_fills_to_the_commit_distance"),
    "X5": M("X5", SWS, "(1.0 - NEW_FAB_MIN_SCALE) * progress.clamp(0.0, 1.0)",
            "(1.0 - NEW_FAB_MIN_SCALE) * progress.min(1.0)",
            "new_fab_scale: lower clamp dropped",
            "the_peel_and_the_fab_scale_clamp_to_the_armed_point"),
    "X6": M("X6", SW,
            "vx.abs() >= CARD_FLING_VEL && travel >= CARD_FLING_MIN_PX && vx.signum() == dx.signum()",
            "vx.abs() >= CARD_FLING_VEL && travel >= CARD_FLING_MIN_PX",
            "should_dismiss_card: an opposite flick dismisses",
            "a_card_dismisses_on_travel_or_a_same_way_flick"),
    "X7": M("X7", SWS, "    (swipe.offset, swipe.offset + sign * width)",
            "    (swipe.offset, swipe.offset - sign * width)",
            "swipe_offsets_px: neighbour tracked on the wrong side",
            "the_slots_follow_the_finger_then_land_a_width_off"),
    "X8": M("X8", SWS,
            "            SwipeMode::Workspace => InlineStyle::new(),\n            SwipeMode::Slide => InlineStyle::new()",
            "            SwipeMode::Workspace | SwipeMode::Slide => InlineStyle::new()",
            "swipe_style_for: a drawer pull slides the current slot",
            "only_the_swiped_slots_move_and_a_slide_tracks_without_transition"),
    "X9": M("X9", SWS, "    let shadow = if progress > 0.0 {", "    let shadow = if progress >= 0.0 {",
            "new_terminal_peel: shadow painted at rest",
            "a_new_terminal_pull_peels_the_current_card"),
    "X10": M("X10", SW, "    if !compact || swipe.mode != SwipeMode::Slide {",
             "    if swipe.mode != SwipeMode::Slide {",
             "bar_neighbor_id: the neighbour bar rides in off compact",
             "only_a_compact_slide_brings_the_neighbours_bar"),
    "X11": M("X11", SWS,
             "    if swipe.mode != SwipeMode::NewTerminal || width <= 0.0 {\n        return hidden();\n    }\n    let area_top",
             "    if width <= 0.0 {\n        return hidden();\n    }\n    let area_top",
             "new_fab_style: shown for a plain slide",
             "the_peek_and_fab_are_inert_outside_a_measured_pull"),
    "X12": M("X12", SWS, "    let opacity = if committing {", "    let opacity = if settling {",
             "new_peek_style: a cancelled pull settles opaque",
             "the_peek_fills_the_terminal_area_and_fades_with_progress"),
    "X13": M("X13", SWS, '        .with("left", px(rect.w - 20.0 - FAB_PX))',
             '        .with("left", px(rect.w - FAB_PX))',
             "new_fab_style: FAB flush to the right edge (inset dropped)",
             "the_fab_rests_inside_the_right_edge_then_blooms_to_the_whole_area"),
    "X14": M("X14", SW, "        let settle_ms = settle_duration_ms(width - travelled, width);",
             "        let settle_ms = settle_duration_ms(travelled, width);",
             "release_swipe: commit settle timed over the travelled, not the remaining, distance",
             "a_release_commits_to_the_neighbour_blooms_a_new_terminal_or_springs_back"),
    # ---- web touch
    "T1": M("T1", TOUCH, "        matches!(self, Self::Armed { .. } | Self::Tracked { .. })",
            "        matches!(self, Self::Tracked { .. })",
            "consumes: the arming move is not consumed",
            "a_horizontal_drag_arms_once_then_tracks_and_is_consumed"),
    "T2": M("T2", TOUCH, "if !compact || touches != 1 || x <= EDGE_PX {", "if !compact || touches != 1 {",
            "step Start: the drawer edge band arms a swipe",
            "a_touch_in_the_drawer_edge_band_or_with_two_fingers_never_arms"),
    "T3": M("T3", TOUCH, "        if self.axis.is_none() {", "        if self.axis != Some(LockedAxis::X) {",
            "track: a vertical lock is re-evaluated on every move",
            "a_vertical_lock_keeps_the_gesture_for_the_terminal_to_the_end"),
    "T4": M("T4", TOUCH,
            "        while self.samples.len() > 1 && self.samples[0].1 < at_ms - RELEASE_WINDOW_MS {\n            self.samples.remove(0);\n        }\n",
            "",
            "release: the release-window trim dropped (velocity over all samples)",
            "the_release_speed_reads_only_the_newest_samples"),
}


def B(crate, ids):
    return dict(crate=crate, mutants=[dict(MUT[i]) for i in ids])


BATCHES = {
    "c1": B("cc", ["DI1", "DI2", "DI3", "DI4", "DI5", "SP1", "TB1", "V1", "W1", "S1", "S8"]),
    "c2": B("cc", ["DI6", "DI7", "DI8", "SP2", "TB2", "V2", "W2", "S2", "S3", "S6", "SI1", "S8"]),
    "c3": B("cc", ["SP3", "TB3", "V3", "V4", "W3", "S4", "S7", "S9", "SI2", "F1"]),
    "c4": B("cc", ["TB4", "V5", "V6", "W4", "S5", "S10", "S11", "SI3", "SI4", "F2"]),
    "c5": B("cc", ["TB5", "V7", "V8", "V9", "F3"]),
    "w1": B("web", ["G1", "G4", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "X9", "X11", "T1"]),
    "w2": B("web", ["G2", "G3", "X8", "X10", "X12", "X13", "X14", "T2", "T3", "T4"]),
}
