// @ts-nocheck
// GENERATED by scripts/gen-embed.ts — do not edit.
// Source-mode workers consume the transitive keeper bundle digest generated here.
export const GENERATED_KEEPER_IMPLEMENTATION_DIGEST: string | null = "58046d911b77e01750ecc27f6fed7582ce3107bbc257e001fa5a47e190e03438";
