// @ts-nocheck
// GENERATED by scripts/gen-embed.ts — do not edit.
// Source-mode workers consume the transitive keeper bundle digest generated here.
export const GENERATED_KEEPER_IMPLEMENTATION_DIGEST: string | null = "6555049118e9d15837184f346984ae0e309aa233cc5894c7686aa4e9ba8b9033";
