// @ts-nocheck
// GENERATED by scripts/gen-embed.ts — do not edit.
// Source-mode workers consume the transitive keeper bundle digest generated here.
export const GENERATED_KEEPER_IMPLEMENTATION_DIGEST: string | null = "ec634833a2c484d62efdcd0b09fedb37ce7b8a76e8427b03b7f1308ed855ed51";
