// Installs the Roost live-chat bridge into omp's user-level extension directory.
//
// omp auto-discovers `<agent dir>/extensions/*.{ts,js}` at USER level
// (@oh-my-pi/pi-coding-agent@17.1.3 `src/discovery/builtin.ts::getConfigDirs` →
// `discoverExtensionModulePaths(path.join(dir, "extensions"))`), and its loader
// accepts a bare factory or a `{ default }` module (`extensions/loader.ts:54-57`).
// User level, NOT project level: project discovery needs `<cwd>/.omp`, and Roost
// panes run in arbitrary directories.
//
// The extension body is `./bridge-extension.js`, imported as TEXT so it ships
// identically whether the worker runs from source or from `bun build --compile`
// (scripts/build-binary.ts) where the source tree is absent. That repo file is the
// single source of truth; the installed copy is regenerated and must never be
// hand-edited.
//
// Machine-level side effect: this writes into `~/.omp/agent/extensions/`, which
// every omp on this machine loads. The extension returns immediately unless
// ROOST_OMP_LIVE_DIR and ROOST_SESSION_ID are set and stdout is a TTY, so a
// non-Roost omp pays two `process.env` reads.

import { existsSync, mkdirSync, readdirSync, readFileSync, realpathSync, rmSync, statSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { log } from "@roost/shared";
import { OMP_LIVE_DIR } from "../../session-constants.ts";
import { resolveOmpBin } from "./rpc-driver.ts";
import BRIDGE_SOURCE from "./bridge-extension.js" with { type: "text" };

const DEST = join(homedir(), ".omp", "agent", "extensions", "roost-chat-bridge.js");

/** How long a bridge sidecar outlives its last write. The bridge opens one
 *  `<sessionId>.ndjson` per omp run and never removes it, so without a prune the
 *  directory grows by one file per omp session forever. A week is far longer
 *  than any live session and leaves recent ones intact for post-mortems. */
const SIDECAR_TTL_MS = 7 * 24 * 60 * 60 * 1000;

/** Delete bridge sidecars nobody has written to in SIDECAR_TTL_MS. Best-effort
 *  and silent: a sidecar still open by a live omp keeps its inode, so an
 *  over-eager unlink would cost that pane its stream, never the worker's boot. */
function pruneStaleSidecars(): void {
	let names: string[];
	try { names = readdirSync(OMP_LIVE_DIR); }
	catch { return; }   // never created — nothing to prune
	const cutoff = Date.now() - SIDECAR_TTL_MS;
	let pruned = 0;
	for (const name of names) {
		if (!name.endsWith(".ndjson")) continue;
		const path = join(OMP_LIVE_DIR, name);
		try {
			if (statSync(path).mtimeMs >= cutoff) continue;
			rmSync(path);
			pruned++;
		} catch { /* raced with a live bridge — leave it */ }
	}
	if (pruned > 0) log.info("omp-bridge", "sidecars_pruned", { count: pruned, dir: OMP_LIVE_DIR });
}

/** Installed omp version, or null when omp is not installed.
 *
 *  Resolution is `resolveOmpBin()` — the SAME resolver the RPC driver spawns
 *  through, so the two can never disagree about which omp is in play. Using
 *  `Bun.which` alone here was a real bug: the worker runs under a LaunchAgent
 *  whose PATH is `/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin`, while a
 *  bun-global install puts omp in `~/.bun/bin` — on an interactive shell's PATH
 *  and nowhere else. It returned null under launchd every time, so the
 *  installer silently did nothing and the bridge was never installed on any
 *  machine that had not had it written by hand.
 *
 *  Package root from `<bin>/omp` → `…/@oh-my-pi/pi-coding-agent/dist/cli.js`
 *  → root, the way apps/web/scripts/sync-omp-tool-views.ts does it. */
function ompVersion(): string | null {
	const bin = resolveOmpBin();
	if (!bin) return null;
	try {
		const root = dirname(dirname(realpathSync(bin)));
		const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8")) as { version?: unknown };
		return typeof pkg.version === "string" ? pkg.version : "unknown";
	} catch {
		return "unknown";
	}
}

/** Write the bridge extension into omp's user extension dir. Idempotent: a
 *  byte-identical existing file is left alone, so boot does not churn mtimes.
 *  No-ops when omp is not installed — LOUDLY, because a silent skip here is
 *  indistinguishable from a successful idempotent run in the log, which is
 *  exactly how the PATH bug above survived. */
export function installOmpBridge(): void {
	pruneStaleSidecars();
	const version = ompVersion();
	if (version === null) {
		log.info("omp-bridge", "skipped_no_omp", { path: process.env.PATH ?? "" });
		return;
	}

	const content = `// GENERATED by @roost/worker — do not edit. Source of truth:\n// apps/worker/src/chat/omp/bridge-extension.js (installed for omp ${version}).\n${BRIDGE_SOURCE}`;

	if (existsSync(DEST) && readFileSync(DEST, "utf8") === content) return;

	mkdirSync(dirname(DEST), { recursive: true, mode: 0o700 });
	writeFileSync(DEST, content, { mode: 0o600 });
	log.info("omp-bridge", "installed", { path: DEST, ompVersion: version });
}
