{{- if .Values.agentHost.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "roost.fullname" . }}-agent-host
  labels:
    {{- include "roost.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.agentHost.storage }}
{{- end }}
