{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "roost.databaseSecret" . }}
  labels:
    {{- include "roost.labels" . | nindent 4 }}
type: Opaque
stringData:
  ROOST_COORDINATOR_DATABASE_URL: {{ include "roost.databaseUrl" . | quote }}
{{- end }}
