//! The terminal-core conformance family: drive the real emulator with the byte
//! sequences in `protocol/conformance/terminal-core/` and assert the state the
//! vector recorded.
//!
//! The vectors come from two places, and which one is named in each vector:
//!
//! - `oracle: "xterm"` — generated by driving `@xterm/headless`, an
//!   implementation with nothing in common with this one. Passing says the Rust
//!   core agrees with an independent terminal.
//! - `oracle: "patch"` — the expected state is written by hand from
//!   `scripts/wterm-0.5.0-roost.patch`, and the vector names the hunk. These
//!   are behaviours the v2 Zig core was patched to have and xterm does not
//!   share; an xterm-derived vector would record the wrong answer, and the
//!   generator prints the difference so it stays visible.
//!
//! A test unwraps the values it is asserting about: a failure there is the
//! assertion failing, which is what a test wants. The workspace denies
//! `unwrap`/`expect` in a running component because a panic on a bad wire value
//! is a fleet-visible outage, and that reasoning does not reach here.

// A behaviour test unwraps the value it is asserting about: a failure there is
// the assertion failing, which is exactly what a test wants. The workspace
// denies `unwrap`/`expect` because a panic on a bad wire value in a running
// component is a fleet-visible outage, and that reasoning does not reach a test.
#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::collections::BTreeMap;
use std::path::PathBuf;

use base64::Engine;
use base64::engine::general_purpose::STANDARD as BASE64;
use roost_protocol::cell::{CellGridFrame, CellSpan, MouseTracking};
use roost_term::{AlacrittyCore, TerminalCore, grid_to_cell_frame};
use serde::Deserialize;

#[derive(Deserialize)]
#[serde(rename_all = "snake_case")]
struct Vector {
    name: String,
    oracle: String,
    /// Present on a `known-divergence` vector: what the v2 core did instead.
    /// The runner prints it rather than failing on it, because the difference
    /// is recorded, named and greppable — which is the point of recording it.
    #[serde(default)]
    diverges_from_v2: Option<String>,
    cols: u16,
    rows: u16,
    #[serde(default)]
    resize: Option<Size>,
    chunks: Vec<String>,
    expected: Expected,
}

#[derive(Deserialize, Clone, PartialEq, Eq)]
struct Size {
    cols: u16,
    rows: u16,
}

#[derive(Debug, Clone, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
struct Expected {
    viewport: Vec<String>,
    scrollback: Vec<String>,
    cursor: Cursor,
    alt_screen: bool,
    modes: Modes,
}

#[derive(Debug, Clone, Deserialize, PartialEq, Eq)]
struct Cursor {
    row: u16,
    col: u16,
}

#[derive(Debug, Clone, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
struct Modes {
    cursor_keys_app: bool,
    bracketed_paste: bool,
    mouse_tracking: u16,
    mouse_sgr: bool,
    focus_events: bool,
}

fn vectors_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("crates/roost-term sits two levels below the repository root")
        .join("protocol/conformance/terminal-core")
}

/// A row's text as the vector records it: the spans' characters, right-trimmed.
fn row_text(spans: &[CellSpan]) -> String {
    row_text_of(
        &spans
            .iter()
            .map(|span| span.text.as_str())
            .collect::<Vec<_>>(),
    )
}

fn row_text_of(cells: &[&str]) -> String {
    cells.concat().trim_end().to_owned()
}

fn view_of(frame: &CellGridFrame) -> (Vec<String>, Vec<String>) {
    let viewport: Vec<String> = frame
        .viewport_rows
        .iter()
        .map(|row| row_text(&row.spans))
        .collect();
    let scrollback: Vec<String> = frame
        .scrollback_rows
        .iter()
        .map(|row| row_text(&row.spans))
        .collect();
    (viewport, scrollback)
}

/// Drive one vector and return everything it asserts.
fn run(vector: &Vector) -> (Expected, String) {
    let mut core = AlacrittyCore::new(vector.cols, vector.rows);
    for (index, encoded) in vector.chunks.iter().enumerate() {
        // Terminal bytes are UTF-8; a wide glyph is three of them. Decoding
        // as Latin-1 would fold each onto one byte and drive a different
        // terminal than the vector names.
        let bytes = BASE64.decode(encoded).unwrap_or_else(|error| {
            panic!("{}: chunk {index} is not base64: {error}", vector.name)
        });
        let text = String::from_utf8(bytes)
            .unwrap_or_else(|error| panic!("{}: chunk {index} is not UTF-8: {error}", vector.name));
        core.write(text.as_bytes());
    }
    if let Some(size) = &vector.resize {
        core.resize(size.cols, size.rows);
    }
    let dropped = core
        .discarded_line_count()
        .expect("the patched core reports its own eviction count");
    let frame = grid_to_cell_frame(&core, 1, "g:0", "stream", None, dropped);
    let (viewport, scrollback) = view_of(&frame);
    let observed = Expected {
        viewport,
        scrollback,
        cursor: Cursor {
            row: frame.cursor_row as u16,
            col: frame.cursor_col as u16,
        },
        alt_screen: frame.alt_screen,
        modes: Modes {
            cursor_keys_app: frame.cursor_keys_app,
            bracketed_paste: frame.bracketed_paste,
            mouse_tracking: match frame.mouse_tracking {
                MouseTracking::PressRelease => 1000,
                MouseTracking::ButtonMotion => 1002,
                MouseTracking::None | MouseTracking::Unknown(_) => 0,
            },
            mouse_sgr: frame.mouse_sgr,
            focus_events: frame.focus_events,
        },
    };
    let rendered = describe(&observed);
    (observed, rendered)
}

fn describe(expected: &Expected) -> String {
    format!(
        "viewport {:?} scrollback {:?} cursor ({},{}) alt {} modes {:?}",
        expected.viewport,
        expected.scrollback,
        expected.cursor.row,
        expected.cursor.col,
        expected.alt_screen,
        expected.modes
    )
}

#[test]
fn every_terminal_core_vector_matches() {
    let directory = vectors_dir();
    let mut paths: Vec<PathBuf> = std::fs::read_dir(&directory)
        .unwrap_or_else(|error| panic!("cannot read {}: {error}", directory.display()))
        .flatten()
        .map(|entry| entry.path())
        .filter(|path| path.extension().is_some_and(|suffix| suffix == "json"))
        .collect();
    paths.sort();
    assert!(!paths.is_empty(), "the terminal-core family is empty");

    let mut failures: Vec<String> = Vec::new();
    let mut divergences: Vec<String> = Vec::new();
    let mut oracles: BTreeMap<String, usize> = BTreeMap::new();
    for path in paths {
        let text = std::fs::read_to_string(&path)
            .unwrap_or_else(|error| panic!("cannot read {}: {error}", path.display()));
        let vector: Vector = serde_json::from_str(&text)
            .unwrap_or_else(|error| panic!("{} is not a vector: {error}", path.display()));
        *oracles.entry(vector.oracle.clone()).or_default() += 1;
        if let Some(divergence) = &vector.diverges_from_v2 {
            divergences.push(format!("{}: {divergence}", vector.name));
        }
        let (observed, rendered) = run(&vector);
        if observed != vector.expected {
            failures.push(format!(
                "{}: expected {}, observed {}",
                vector.name,
                describe(&vector.expected),
                rendered
            ));
        } else {
            println!("ok   terminal-core/{}", vector.name);
        }
    }
    println!("\noracles: {oracles:?}");
    if !divergences.is_empty() {
        println!(
            "\n{} known divergence(s) from the v2 patched core — these are the\n\
             behaviours this core does NOT yet have:\n  {}\n",
            divergences.len(),
            divergences.join("\n  ")
        );
    }
    assert!(
        oracles.contains_key("xterm") && oracles.contains_key("patch"),
        "the family must carry both oracles or it is not testing what it claims"
    );
    assert!(
        failures.is_empty(),
        "\n{} terminal-core vector(s) failed:\n  {}\n",
        failures.len(),
        failures.join("\n  ")
    );
}
