// @ts-nocheck
// GENERATED by scripts/gen-embed.ts — do not edit.
import coord from "../../../apps/coord/scripts/install.sh" with { type: "text" };
import worker from "../../../apps/worker/scripts/install.sh" with { type: "text" };
export const COORD_INSTALL_SH = coord;
export const WORKER_INSTALL_SH = worker;
