// @ts-nocheck
// GENERATED by scripts/gen-embed.ts — do not edit.
// Empty stub: from-source runs serve the SPA from disk (cfg.webDistPath).
export const WEB_ASSETS: Map<string, { raw: string; gzip?: string }> = new Map();
