//! Compiles the wire contract in `protocol/proto/roost/v1/` into buffa message
//! types and ConnectRPC service stubs. Nothing else in the workspace reads the
//! `.proto` tree, and nothing in it hand-writes a message type.
//!
//! The descriptors come from `protox`, a protobuf compiler written in Rust,
//! rather than a `protoc` or `buf` binary on PATH. That is a deliberate
//! trade: it adds a build-only dependency but removes an unversioned external
//! toolchain from every developer's machine and from CI, and it makes the
//! generated bytes a function of `Cargo.lock` alone. `prost` reaches the
//! build graph through `protox::prost` and stops there — the shipped runtime
//! is buffa alone.

// A build script has no error channel: a failed compile is the only way to
// report a bad descriptor set or a missing `.proto`, and a `Result` nobody
// reads is a silent failure instead. The workspace denies `expect` in product
// code because a panic there is a fleet-visible outage; in here it is a build
// failure with the message already attached.
#![allow(clippy::expect_used, clippy::unwrap_used)]

use std::path::{Path, PathBuf};

/// The module-tree file `connectrpc::include_generated!()` reads.
const GENERATED_INCLUDE_FILE: &str = "_connectrpc.rs";

fn main() {
    let proto_root = repository_root().join("protocol/proto");
    let package_dir = proto_root.join("roost/v1");
    let proto_files = proto_sources(&package_dir);

    for file in &proto_files {
        println!("cargo:rerun-if-changed={}", file.display());
    }

    let descriptor_path = compile_descriptors(&proto_files, &proto_root);
    connectrpc_build::Config::new()
        .descriptor_set(&descriptor_path)
        .files(&proto_relative_names(&proto_files, &proto_root))
        .include_file(GENERATED_INCLUDE_FILE)
        .compile()
        .unwrap_or_else(|error| panic!("connectrpc codegen failed: {error:?}"));
}

fn compile_descriptors(proto_files: &[PathBuf], proto_root: &Path) -> PathBuf {
    let mut descriptors = protox::compile(proto_files, [proto_root])
        .unwrap_or_else(|error| panic!("protox could not compile the wire contract: {error:?}"));
    assign_default_json_names(&mut descriptors);
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("cargo always sets OUT_DIR"));
    let descriptor_path = out_dir.join("roost-wire-descriptors.bin");
    let mut encoded = Vec::new();
    protox::prost::Message::encode(&descriptors, &mut encoded)
        .expect("encoding a FileDescriptorSet into a Vec cannot fail");
    std::fs::write(&descriptor_path, encoded)
        .unwrap_or_else(|error| panic!("cannot write {}: {error}", descriptor_path.display()));
    descriptor_path
}

/// Fill in the canonical protobuf JSON name of every field that does not
/// declare one explicitly.
///
/// `protoc` computes a `json_name` for every field and buffa uses it verbatim
/// as the field's `serde(rename)`. `protox` only records the name when the
/// `.proto` spells an explicit `[json_name = …]` option, so without this pass
/// the generated types deserialize `fg_rgb` where a Connect JSON client, a
/// `curl` body, and every committed conformance vector all send `fgRgb` — the
/// error would be invisible until a browser failed to parse a frame.
fn assign_default_json_names(descriptors: &mut prost_types::FileDescriptorSet) {
    for file in &mut descriptors.file {
        assign_message_json_names(&mut file.message_type);
        for extension in &mut file.extension {
            assign_json_name(extension);
        }
    }
}

fn assign_message_json_names(messages: &mut [prost_types::DescriptorProto]) {
    for message in messages {
        for field in &mut message.field {
            assign_json_name(field);
        }
        for extension in &mut message.extension {
            assign_json_name(extension);
        }
        assign_message_json_names(&mut message.nested_type);
    }
}

fn assign_json_name(field: &mut prost_types::FieldDescriptorProto) {
    if field.json_name.is_some() {
        return;
    }
    let Some(name) = field.name.as_deref() else {
        return;
    };
    field.json_name = Some(default_json_name(name));
}

/// protobuf's own `ToJsonName`: drop an underscore and uppercase the letter
/// after it, except when that letter is a digit — an underscore before a digit
/// is load-bearing and is kept, so `chunk_1` stays `chunk_1` rather than
/// becoming `chunk1`.
fn default_json_name(field_name: &str) -> String {
    let mut json = String::with_capacity(field_name.len());
    let mut capitalize_next = false;
    let mut previous_was_underscore = false;
    for character in field_name.chars() {
        if capitalize_next && !character.is_ascii_digit() {
            json.extend(character.to_uppercase());
            capitalize_next = false;
            continue;
        }
        capitalize_next = false;
        match character {
            '_' => {
                capitalize_next = true;
                previous_was_underscore = true;
            }
            other => {
                // A second underscore in a row stays: protoc has no rule to
                // collapse them, and inventing one would change the name.
                if !previous_was_underscore || other.is_ascii_digit() {
                    json.push(other);
                }
                previous_was_underscore = false;
            }
        }
    }
    json
}

/// Every `.proto` under the package directory, in a stable order so the
/// generated output does not depend on the filesystem's readdir order.
fn proto_sources(package_dir: &Path) -> Vec<PathBuf> {
    let entries = std::fs::read_dir(package_dir)
        .unwrap_or_else(|error| panic!("cannot read {}: {error}", package_dir.display()));
    let mut sources: Vec<PathBuf> = entries
        .flatten()
        .map(|entry| entry.path())
        .filter(|path| path.extension().is_some_and(|suffix| suffix == "proto"))
        .collect();
    sources.sort();
    assert!(
        !sources.is_empty(),
        "no .proto files under {} — the wire contract is missing, not optional",
        package_dir.display()
    );
    sources
}

/// The names as they appear inside the descriptor set, which is what
/// `Config::files` selects on. A descriptor's `name` is the path relative to
/// the include root (`roost/v1/wire.proto`), not the absolute path we read.
fn proto_relative_names(proto_files: &[PathBuf], proto_root: &Path) -> Vec<String> {
    proto_files
        .iter()
        .map(|path| {
            let relative = path.strip_prefix(proto_root).unwrap_or(path);
            relative
                .components()
                .map(|component| component.as_os_str().to_string_lossy().into_owned())
                .collect::<Vec<_>>()
                .join("/")
        })
        .collect()
}

fn repository_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("crates/roost-proto always sits two levels below the repository root")
        .to_path_buf()
}
