#!/usr/bin/env bun
// Generates assets that `bun build --compile` bakes into the single `roost`
// binary: the SPA, migrations, wterm wasm, service installers, agent
// integrations, keeper contract, and canonical ROOST skill. build-binary.ts
// requests full embeds before compilation and `--stub` afterward so source
// commands read their canonical files from disk.
import { mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { extname, join, relative } from "node:path";
import { composeStandaloneIntegration } from "../apps/worker/src/agent-status/standalone-integration.ts";
import { AGENT_INTEGRATION_ASSET_SPECS } from "../apps/worker/src/agent-status/integration-assets.ts";
import { buildKeeperImplementationDigest } from "./keeper-bundle-digest.ts";

const WEB_OUT = "apps/coord/src/web-embed.generated.ts";
const WEB_GZIP_OUT = "apps/coord/src/web-embed.generated-assets";
const MIGR_OUT = "apps/coord/src/migrations-embed.generated.ts";
const WASM_OUT = "apps/shared/src/wterm-wasm-embed.generated.ts";
const SCRIPTS_OUT = "apps/shared/src/install-scripts.generated.ts";
const AGENT_INTEGRATIONS_OUT = "apps/worker/src/agent-status/integration-assets.generated.ts";
const KEEPER_CONTRACT_OUT = "apps/worker/src/keeper/keeper-contract.generated.ts";
const SKILL_OUT = "apps/roost-cli/src/skill-embed.generated.ts";
const HDR = "// @ts-nocheck\n// GENERATED by scripts/gen-embed.ts — do not edit.\n";
const COMPRESSIBLE_WEB_EXTENSIONS: Record<string, true> = {
  ".js": true,
  ".mjs": true,
  ".css": true,
  ".html": true,
  ".json": true,
  ".svg": true,
  ".map": true,
  ".txt": true,
  ".webmanifest": true,
};
const DIST = "apps/web/dist";
const MIGR = "apps/coord/migrations";

/** Manifest keys are URL paths, even when the generator runs on Windows. */
export function normalizeManifestUrlKey(path: string): string {
  return path.replaceAll("\\", "/");
}

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...walk(p));
    else out.push(p);
  }
  return out.sort();
}

async function generate(): Promise<void> {
  // Always remove an interrupted prior run before walking the SPA or writing
  // stubs. Generated gzip files exist only long enough for `bun build` to
  // embed them.
  rmSync(WEB_GZIP_OUT, { recursive: true, force: true });
  const suppliedKeeperDigest = process.env.ROOST_GENERATED_KEEPER_IMPLEMENTATION_DIGEST;
  const keeperImplementationDigest = suppliedKeeperDigest
    ?? await buildKeeperImplementationDigest();
  if (!/^[0-9a-f]{64}$/.test(keeperImplementationDigest)) {
    throw new Error("generated keeper implementation digest is invalid");
  }
  writeFileSync(
    KEEPER_CONTRACT_OUT,
    `${HDR}// Source-mode workers consume the transitive keeper bundle digest generated here.\nexport const GENERATED_KEEPER_IMPLEMENTATION_DIGEST: string | null = ${JSON.stringify(keeperImplementationDigest)};\n`,
  );

  if (process.argv.includes("--stub")) {
    writeFileSync(WEB_OUT, `${HDR}// Empty stub: from-source runs serve the SPA from disk (cfg.webDistPath).\nexport const WEB_ASSETS: Map<string, { raw: string; gzip?: string }> = new Map();\n`);
    writeFileSync(MIGR_OUT, `${HDR}// Empty stub: from-source runs read apps/coord/migrations/*.sql.\nexport const MIGRATIONS: { name: string; sql: string }[] = [];\n`);
    writeFileSync(WASM_OUT, `${HDR}// Empty stub: from-source loads the wasm and its digest sidecar from disk (import.meta.url).\nexport const WTERM_WASM_EMBED: string | null = null;\nexport const WTERM_WASM_SHA256_EMBED: string | null = null;\n`);
    writeFileSync(AGENT_INTEGRATIONS_OUT, `${HDR}// Empty stub: from-source worker reads integration assets from disk.\nimport type { EmbeddedAgentIntegrationAsset } from "./integration-assets.ts";\nexport const AGENT_INTEGRATION_ASSETS: readonly EmbeddedAgentIntegrationAsset[] = [];\n`);
    writeFileSync(SKILL_OUT, `${HDR}// Empty stub: from-source CLI reads skills/roost/SKILL.md from disk.\nexport const ROOST_SKILL_EMBED: string | null = null;\n`);
    console.log("gen-embed: wrote empty stubs + keeper contract");
    return;
  }

  // ── web assets: raw files plus build-time gzip variants for text assets.
  // Both variants use type "file", so compiled production serves embedded
  // bytes directly without request-time compression or filesystem probes.
  const webFiles = walk(DIST);
  const webLines: string[] = [HDR.trimEnd(), ""];
  const webEntries: string[] = [];
  mkdirSync(WEB_GZIP_OUT, { recursive: true });
  webFiles.forEach((abs, i) => {
    const rel = normalizeManifestUrlKey(relative(DIST, abs));
    webLines.push(`import w${i} from ${JSON.stringify(`../../web/dist/${rel}`)} with { type: "file" };`);
    if (COMPRESSIBLE_WEB_EXTENSIONS[extname(rel).toLowerCase()]) {
      const gzipName = `${i}.gz`;
      writeFileSync(join(WEB_GZIP_OUT, gzipName), Bun.gzipSync(readFileSync(abs)));
      webLines.push(`import g${i} from ${JSON.stringify(`./web-embed.generated-assets/${gzipName}`)} with { type: "file" };`);
      webEntries.push(`  [${JSON.stringify(rel)}, { raw: w${i}, gzip: g${i} }],`);
    } else {
      webEntries.push(`  [${JSON.stringify(rel)}, { raw: w${i} }],`);
    }
  });
  webLines.push("", "export const WEB_ASSETS: Map<string, { raw: string; gzip?: string }> = new Map([", ...webEntries, "]);", "");
  writeFileSync(WEB_OUT, webLines.join("\n"));

  // ── migrations: type "text" → SQL inlined as string constants.
  const migrFiles = walk(MIGR).filter((f) => f.endsWith(".sql"));
  const migrLines: string[] = [HDR.trimEnd(), ""];
  const migrEntries: string[] = [];
  migrFiles.forEach((abs, i) => {
    const file = normalizeManifestUrlKey(relative(MIGR, abs));
    const name = file.replace(/\.sql$/, "");
    migrLines.push(`import m${i} from "../migrations/${file}" with { type: "text" };`);
    migrEntries.push(`  { name: "${name}", sql: m${i} },`);
  });
  migrLines.push("", "export const MIGRATIONS: { name: string; sql: string }[] = [", ...migrEntries, "];", "");
  writeFileSync(MIGR_OUT, migrLines.join("\n"));

  // ── wterm wasm: single file, type "file" → loaded via Bun.file server-side.
  // Its sha256sum sidecar rides along as text so the compiled binary verifies
  // the embedded bytes against the same recorded digest a from-source run does.
  writeFileSync(WASM_OUT, `${HDR}import wasm from "../wasm/wterm-roost.wasm" with { type: "file" };\nimport wasmSha256 from "../wasm/wterm-roost.wasm.sha256" with { type: "text" };\nexport const WTERM_WASM_EMBED: string | null = wasm;\nexport const WTERM_WASM_SHA256_EMBED: string | null = wasmSha256;\n`);

  // ── LaunchAgent install scripts: type "text" → run in binary-mode quickstart.
  writeFileSync(SCRIPTS_OUT, `${HDR}import coord from "../../coord/scripts/install.sh" with { type: "text" };\nimport worker from "../../worker/scripts/install.sh" with { type: "text" };\nexport const COORD_INSTALL_SH = coord;\nexport const WORKER_INSTALL_SH = worker;\n`);

  // ── Canonical skill: type "text" preserves the release-matched UTF-8 bytes.
  writeFileSync(SKILL_OUT, `${HDR}import roostSkill from "../../../skills/roost/SKILL.md" with { type: "text" };\nexport const ROOST_SKILL_EMBED: string | null = roostSkill;\n`);

  // ── OMP/Pi extensions: source text installed into user config dirs.
  // The deployed text must be standalone (no @roost/* imports survive in user
  // config dirs), so bake the SAME catalog/composition the source installer uses.
  const reportTransport = readFileSync(
    "apps/worker/src/agent-status/report-transport.ts",
    "utf8",
  );
  const agentIntegrations = AGENT_INTEGRATION_ASSET_SPECS.map((spec) => ({
    id: spec.id,
    content: composeStandaloneIntegration(
      readFileSync(
        join("apps/worker/src/agent-status", spec.sourcePath),
        "utf8",
      ),
      reportTransport,
    ),
  }));
  writeFileSync(
    AGENT_INTEGRATIONS_OUT,
    `${HDR}import type { EmbeddedAgentIntegrationAsset } from "./integration-assets.ts";\nexport const AGENT_INTEGRATION_ASSETS: readonly EmbeddedAgentIntegrationAsset[] = ${JSON.stringify(agentIntegrations)};\n`,
  );

  console.log(`gen-embed: ${webFiles.length} web assets, ${migrFiles.length} migrations, 1 wasm, 2 install scripts, ${agentIntegrations.length} agent integrations, 1 keeper contract, 1 skill`);
}

if (import.meta.main) await generate();
