#!/usr/bin/env bun
// Generate the embed manifests that let `bun build --compile` bake the SPA
// (apps/web/dist), the coord migrations, the server-side wterm wasm, and the
// LaunchAgent install scripts into the single `roost` binary. Run by
// scripts/build-binary.ts before the compile; `--stub` restores empty
// manifests afterward so the working tree stays clean (from-source runs use
// the on-disk paths). Consumers: apps/coord/src/main.ts (WEB_ASSETS),
// db/migrate.ts (MIGRATIONS), apps/shared/src/wterm-wasm.ts (WTERM_WASM_EMBED),
// apps/roost-cli/src/install-binary-agents.ts (COORD/WORKER_INSTALL_SH).
import { mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { extname, join, relative } from "node:path";

const WEB_OUT = "apps/coord/src/web-embed.generated.ts";
const WEB_GZIP_OUT = "apps/coord/src/web-embed.generated-assets";
const MIGR_OUT = "apps/coord/src/migrations-embed.generated.ts";
const WASM_OUT = "apps/shared/src/wterm-wasm-embed.generated.ts";
const SCRIPTS_OUT = "apps/shared/src/install-scripts.generated.ts";
const AGENT_INTEGRATIONS_OUT = "apps/worker/src/agent-status/integration-assets.generated.ts";
const HDR = "// @ts-nocheck\n// GENERATED by scripts/gen-embed.ts — do not edit.\n";
const COMPRESSIBLE_WEB_EXTENSIONS: Record<string, true> = {
  ".js": true,
  ".mjs": true,
  ".css": true,
  ".html": true,
  ".json": true,
  ".svg": true,
  ".map": true,
  ".txt": true,
  ".webmanifest": true,
};
const DIST = "apps/web/dist";
const MIGR = "apps/coord/migrations";

/** Manifest keys are URL paths, even when the generator runs on Windows. */
export function normalizeManifestUrlKey(path: string): string {
  return path.replaceAll("\\", "/");
}

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...walk(p));
    else out.push(p);
  }
  return out.sort();
}

function generate(): void {
  // Always remove an interrupted prior run before walking the SPA or writing
  // stubs. Generated gzip files exist only long enough for `bun build` to
  // embed them.
  rmSync(WEB_GZIP_OUT, { recursive: true, force: true });

  if (process.argv.includes("--stub")) {
    writeFileSync(WEB_OUT, `${HDR}// Empty stub: from-source runs serve the SPA from disk (cfg.webDistPath).\nexport const WEB_ASSETS: Map<string, { raw: string; gzip?: string }> = new Map();\n`);
    writeFileSync(MIGR_OUT, `${HDR}// Empty stub: from-source runs read apps/coord/migrations/*.sql.\nexport const MIGRATIONS: { name: string; sql: string }[] = [];\n`);
    writeFileSync(WASM_OUT, `${HDR}// Empty stub: from-source loads the wasm and its digest sidecar from disk (import.meta.url).\nexport const WTERM_WASM_EMBED: string | null = null;\nexport const WTERM_WASM_SHA256_EMBED: string | null = null;\n`);
    writeFileSync(AGENT_INTEGRATIONS_OUT, `${HDR}// Empty stub: from-source worker reads integration assets from disk.\nexport const OMP_AGENT_INTEGRATION = "";\nexport const PI_AGENT_INTEGRATION = "";\n`);
    console.log("gen-embed: wrote empty stubs");
    return;
  }

  // ── web assets: raw files plus build-time gzip variants for text assets.
  // Both variants use type "file", so compiled production serves embedded
  // bytes directly without request-time compression or filesystem probes.
  const webFiles = walk(DIST);
  const webLines: string[] = [HDR.trimEnd(), ""];
  const webEntries: string[] = [];
  mkdirSync(WEB_GZIP_OUT, { recursive: true });
  webFiles.forEach((abs, i) => {
    const rel = normalizeManifestUrlKey(relative(DIST, abs));
    webLines.push(`import w${i} from ${JSON.stringify(`../../web/dist/${rel}`)} with { type: "file" };`);
    if (COMPRESSIBLE_WEB_EXTENSIONS[extname(rel).toLowerCase()]) {
      const gzipName = `${i}.gz`;
      writeFileSync(join(WEB_GZIP_OUT, gzipName), Bun.gzipSync(readFileSync(abs)));
      webLines.push(`import g${i} from ${JSON.stringify(`./web-embed.generated-assets/${gzipName}`)} with { type: "file" };`);
      webEntries.push(`  [${JSON.stringify(rel)}, { raw: w${i}, gzip: g${i} }],`);
    } else {
      webEntries.push(`  [${JSON.stringify(rel)}, { raw: w${i} }],`);
    }
  });
  webLines.push("", "export const WEB_ASSETS: Map<string, { raw: string; gzip?: string }> = new Map([", ...webEntries, "]);", "");
  writeFileSync(WEB_OUT, webLines.join("\n"));

  // ── migrations: type "text" → SQL inlined as string constants.
  const migrFiles = walk(MIGR).filter((f) => f.endsWith(".sql"));
  const migrLines: string[] = [HDR.trimEnd(), ""];
  const migrEntries: string[] = [];
  migrFiles.forEach((abs, i) => {
    const file = normalizeManifestUrlKey(relative(MIGR, abs));
    const name = file.replace(/\.sql$/, "");
    migrLines.push(`import m${i} from "../migrations/${file}" with { type: "text" };`);
    migrEntries.push(`  { name: "${name}", sql: m${i} },`);
  });
  migrLines.push("", "export const MIGRATIONS: { name: string; sql: string }[] = [", ...migrEntries, "];", "");
  writeFileSync(MIGR_OUT, migrLines.join("\n"));

  // ── wterm wasm: single file, type "file" → loaded via Bun.file server-side.
  // Its sha256sum sidecar rides along as text so the compiled binary verifies
  // the embedded bytes against the same recorded digest a from-source run does.
  writeFileSync(WASM_OUT, `${HDR}import wasm from "../wasm/wterm-roost.wasm" with { type: "file" };\nimport wasmSha256 from "../wasm/wterm-roost.wasm.sha256" with { type: "text" };\nexport const WTERM_WASM_EMBED: string | null = wasm;\nexport const WTERM_WASM_SHA256_EMBED: string | null = wasmSha256;\n`);

  // ── LaunchAgent install scripts: type "text" → run in binary-mode quickstart.
  writeFileSync(SCRIPTS_OUT, `${HDR}import coord from "../../coord/scripts/install.sh" with { type: "text" };\nimport worker from "../../worker/scripts/install.sh" with { type: "text" };\nexport const COORD_INSTALL_SH = coord;\nexport const WORKER_INSTALL_SH = worker;\n`);

  // ── OMP/Pi lifecycle extensions: source text installed into user config dirs.
  const ompIntegration = readFileSync("apps/worker/src/agent-status/integrations/omp/roost-agent-state.ts", "utf8");
  const piIntegration = readFileSync("apps/worker/src/agent-status/integrations/pi/roost-agent-state.ts", "utf8");
  writeFileSync(
    AGENT_INTEGRATIONS_OUT,
    `${HDR}export const OMP_AGENT_INTEGRATION = ${JSON.stringify(ompIntegration)};\nexport const PI_AGENT_INTEGRATION = ${JSON.stringify(piIntegration)};\n`,
  );

  console.log(`gen-embed: ${webFiles.length} web assets, ${migrFiles.length} migrations, 1 wasm, 2 install scripts, 2 agent integrations`);
}

if (import.meta.main) generate();
