#!/usr/bin/env bun
// Generate the embed manifests that let `bun build --compile` bake the SPA
// (apps/web/dist), the coord migrations, the server-side wterm wasm, and the
// LaunchAgent install scripts into the single `roost` binary. Run by
// scripts/build-binary.ts before the compile; `--stub` restores empty
// manifests afterward so the working tree stays clean (from-source runs use
// the on-disk paths). Consumers: apps/coord/src/main.ts (WEB_ASSETS),
// db/migrate.ts (MIGRATIONS), apps/shared/src/wterm-wasm.ts (WTERM_WASM_EMBED),
// apps/roost-cli/src/install-binary-agents.ts (COORD/WORKER_INSTALL_SH).
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const WEB_OUT = "apps/coord/src/web-embed.generated.ts";
const MIGR_OUT = "apps/coord/src/migrations-embed.generated.ts";
const WASM_OUT = "apps/shared/src/wterm-wasm-embed.generated.ts";
const SCRIPTS_OUT = "apps/roost-cli/src/scripts-embed.generated.ts";
const HDR = "// @ts-nocheck\n// GENERATED by scripts/gen-embed.ts — do not edit.\n";

if (process.argv.includes("--stub")) {
  writeFileSync(WEB_OUT, `${HDR}// Empty stub: from-source runs serve the SPA from disk (cfg.webDistPath).\nexport const WEB_ASSETS: Map<string, string> = new Map();\n`);
  writeFileSync(MIGR_OUT, `${HDR}// Empty stub: from-source runs read apps/coord/migrations/*.sql.\nexport const MIGRATIONS: { name: string; sql: string }[] = [];\n`);
  writeFileSync(WASM_OUT, `${HDR}// Empty stub: from-source loads the wasm from disk (import.meta.url).\nexport const WTERM_WASM_EMBED: string | null = null;\n`);
  writeFileSync(SCRIPTS_OUT, `${HDR}// Empty stub: from-source quickstart runs the on-disk install scripts.\nexport const COORD_INSTALL_SH = "";\nexport const WORKER_INSTALL_SH = "";\n`);
  console.log("gen-embed: wrote empty stubs");
  process.exit(0);
}

const DIST = "apps/web/dist";
const MIGR = "apps/coord/migrations";

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...walk(p));
    else out.push(p);
  }
  return out.sort();
}

// ── web assets: type "file" → streamed via Bun.file (incl. binary wasm/fonts).
const webFiles = walk(DIST);
const webLines: string[] = [HDR.trimEnd(), ""];
const webEntries: string[] = [];
webFiles.forEach((abs, i) => {
  const rel = relative(DIST, abs);
  webLines.push(`import w${i} from "../../web/dist/${rel}" with { type: "file" };`);
  webEntries.push(`  ["${rel}", w${i}],`);
});
webLines.push("", "export const WEB_ASSETS: Map<string, string> = new Map([", ...webEntries, "]);", "");
writeFileSync(WEB_OUT, webLines.join("\n"));

// ── migrations: type "text" → SQL inlined as string constants.
const migrFiles = walk(MIGR).filter((f) => f.endsWith(".sql"));
const migrLines: string[] = [HDR.trimEnd(), ""];
const migrEntries: string[] = [];
migrFiles.forEach((abs, i) => {
  const file = relative(MIGR, abs);
  const name = file.replace(/\.sql$/, "");
  migrLines.push(`import m${i} from "../migrations/${file}" with { type: "text" };`);
  migrEntries.push(`  { name: "${name}", sql: m${i} },`);
});
migrLines.push("", "export const MIGRATIONS: { name: string; sql: string }[] = [", ...migrEntries, "];", "");
writeFileSync(MIGR_OUT, migrLines.join("\n"));

// ── wterm wasm: single file, type "file" → loaded via Bun.file server-side.
writeFileSync(WASM_OUT, `${HDR}import wasm from "../wasm/wterm-roost.wasm" with { type: "file" };\nexport const WTERM_WASM_EMBED: string | null = wasm;\n`);

// ── LaunchAgent install scripts: type "text" → run in binary-mode quickstart.
writeFileSync(SCRIPTS_OUT, `${HDR}import coord from "../../coord/scripts/install.sh" with { type: "text" };\nimport worker from "../../worker/scripts/install.sh" with { type: "text" };\nexport const COORD_INSTALL_SH = coord;\nexport const WORKER_INSTALL_SH = worker;\n`);

console.log(`gen-embed: ${webFiles.length} web assets, ${migrFiles.length} migrations, 1 wasm, 2 install scripts`);
