#!/usr/bin/env bun
// Downloads and verifies the release-specific node-datachannel addon before a
// compiled worker build embeds it. Callers use the serialized staging boundary
// so a foreign addon cannot survive into the next target's compilation.
// The source loader is restored byte-for-byte after every staged operation.
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { chmod, copyFile, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { gunzipSync } from "node:zlib";

const ARCHIVE_LIMIT_BYTES = 32 * 1024 * 1024;
const TAR_LIMIT_BYTES = 64 * 1024 * 1024;
const FETCH_DEADLINE_MS = 30_000;
const ADDON_MEMBER = "package/node_datachannel.node";
const REPOSITORY_ROOT = join(import.meta.dir, "..");
const GENERATED_LOADER_PATH = join(REPOSITORY_ROOT, "apps/worker/src/terminal-peer-native.generated.ts");
const STAGED_ADDON_PATH = join(REPOSITORY_ROOT, "apps/worker/src/terminal-peer.node");
const EMBEDDED_LOADER_SOURCE = `// GENERATED by scripts/terminal-peer-native-assets.ts — do not edit.
// The literal relative require makes Bun embed this N-API addon in compiled outputs.

import type { TerminalPeerNative } from "./terminal-peer-native.ts";

export function loadEmbeddedTerminalPeerNative(): TerminalPeerNative | null {
  return require("./terminal-peer.node") as TerminalPeerNative;
}
`;

const terminalPeerNativeTargetValues = [
  "bun-darwin-arm64",
  "bun-darwin-x64",
  "bun-linux-x64",
  "bun-linux-arm64",
] as const;

export type TerminalPeerNativeTarget = typeof terminalPeerNativeTargetValues[number];
export type TerminalPeerNativeStageOperation<Result> = () => Result | Promise<Result>;

const terminalPeerNativeSuffixByTarget: Readonly<Record<TerminalPeerNativeTarget, string>> = {
  "bun-darwin-arm64": "darwin-arm64",
  "bun-darwin-x64": "darwin-x64",
  "bun-linux-x64": "linux-x64-gnu",
  "bun-linux-arm64": "linux-arm64-gnu",
};
const terminalPeerTargetByHost: Readonly<Record<string, TerminalPeerNativeTarget | undefined>> = {
  "darwin:arm64": "bun-darwin-arm64",
  "darwin:x64": "bun-darwin-x64",
  "linux:x64": "bun-linux-x64",
  "linux:arm64": "bun-linux-arm64",
};

interface TerminalPeerNativeAsset {
  target: TerminalPeerNativeTarget;
  tarball: string;
  integrity: string;
}

interface TerminalPeerNativeManifest {
  member: string;
  assets: ReadonlyMap<TerminalPeerNativeTarget, TerminalPeerNativeAsset>;
}

interface ManifestEntry {
  target: string;
  package: string;
  version: string;
  suffix: string;
  tarball: string;
  integrity: string;
}

const terminalPeerNativeManifest = loadTerminalPeerNativeManifest();

export function isTerminalPeerNativeTarget(value: string): value is TerminalPeerNativeTarget {
  return (terminalPeerNativeTargetValues as readonly string[]).includes(value);
}

export function hostTerminalPeerTarget(): TerminalPeerNativeTarget {
  const host = `${process.platform}:${process.arch}`;
  const target = terminalPeerTargetByHost[host];
  if (!target) throw new Error(`node-datachannel has no pinned release addon for host ${host}`);
  return target;
}

export function stageTerminalPeerNative<Result>(
  target: TerminalPeerNativeTarget,
  operation: TerminalPeerNativeStageOperation<Result>,
): Promise<Result> {
  return terminalPeerNativeStaging.stage(target, operation);
}

class TerminalPeerNativeStaging {
  #tail: Promise<void> = Promise.resolve();

  async stage<Result>(
    target: TerminalPeerNativeTarget,
    operation: TerminalPeerNativeStageOperation<Result>,
  ): Promise<Result> {
    const previousStage = this.#tail;
    let releaseStage: () => void = () => undefined;
    this.#tail = new Promise<void>((resolve) => {
      releaseStage = resolve;
    });
    await previousStage;
    try {
      return await stageTerminalPeerNativeTarget(target, operation);
    } finally {
      releaseStage();
    }
  }
}

const terminalPeerNativeStaging = new TerminalPeerNativeStaging();

async function stageTerminalPeerNativeTarget<Result>(
  target: TerminalPeerNativeTarget,
  operation: TerminalPeerNativeStageOperation<Result>,
): Promise<Result> {
  const asset = terminalPeerNativeManifest.assets.get(target);
  if (!asset) throw new Error(`unsupported terminal peer native target ${target}`);

  const originalLoader = await readFile(GENERATED_LOADER_PATH);
  const stagingDirectory = await mkdtemp(join(tmpdir(), "roost-terminal-peer-native-"));
  let loaderMayHaveChanged = false;
  try {
    await chmod(stagingDirectory, 0o700);
    await rm(STAGED_ADDON_PATH, { force: true });

    const archive = await fetchArchive(asset);
    verifyArchiveIntegrity(archive, asset.integrity);
    const addon = extractAddon(gunzipArchive(archive), terminalPeerNativeManifest.member);
    const privateAddonPath = join(stagingDirectory, "terminal-peer.node");
    await writeFile(privateAddonPath, addon, { mode: 0o600 });
    await copyFile(privateAddonPath, STAGED_ADDON_PATH);
    await chmod(STAGED_ADDON_PATH, 0o600);

    loaderMayHaveChanged = true;
    await writeFile(GENERATED_LOADER_PATH, EMBEDDED_LOADER_SOURCE);
    return await operation();
  } finally {
    const cleanup = await Promise.allSettled([
      restoreSourceArtifacts(originalLoader, loaderMayHaveChanged),
      rm(stagingDirectory, { recursive: true, force: true }),
    ]);
    const cleanupErrors = cleanup
      .filter((result): result is PromiseRejectedResult => result.status === "rejected")
      .map((result) => result.reason);
    if (cleanupErrors.length > 0) {
      throw new AggregateError(cleanupErrors, "could not restore terminal peer native staging");
    }
  }
}

async function restoreSourceArtifacts(originalLoader: Uint8Array, loaderMayHaveChanged: boolean): Promise<void> {
  const cleanup = await Promise.allSettled([
    loaderMayHaveChanged ? writeFile(GENERATED_LOADER_PATH, originalLoader) : Promise.resolve(),
    rm(STAGED_ADDON_PATH, { force: true }),
  ]);
  const cleanupErrors = cleanup
    .filter((result): result is PromiseRejectedResult => result.status === "rejected")
    .map((result) => result.reason);
  if (cleanupErrors.length > 0) {
    throw new AggregateError(cleanupErrors, "could not restore terminal peer source artifacts");
  }
}

async function fetchArchive(asset: TerminalPeerNativeAsset): Promise<Uint8Array> {
  let response: Response;
  try {
    response = await fetch(asset.tarball, { signal: AbortSignal.timeout(FETCH_DEADLINE_MS) });
  } catch (error) {
    throw new Error(`could not fetch terminal peer addon for ${asset.target}`, { cause: error });
  }
  if (!response.ok) throw new Error(`terminal peer addon fetch failed for ${asset.target}: HTTP ${response.status}`);

  const declaredLength = response.headers.get("content-length");
  if (declaredLength !== null) {
    if (!/^\d+$/.test(declaredLength)) throw new Error(`terminal peer addon returned an invalid content length for ${asset.target}`);
    const length = Number(declaredLength);
    if (!Number.isSafeInteger(length) || length > ARCHIVE_LIMIT_BYTES) {
      throw new Error(`terminal peer addon archive exceeds the ${ARCHIVE_LIMIT_BYTES}-byte limit for ${asset.target}`);
    }
  }
  if (!response.body) throw new Error(`terminal peer addon returned no response body for ${asset.target}`);

  const reader = response.body.getReader();
  const chunks: Uint8Array[] = [];
  let byteLength = 0;
  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      if (!value) throw new Error(`terminal peer addon stream ended without data for ${asset.target}`);
      byteLength += value.byteLength;
      if (byteLength > ARCHIVE_LIMIT_BYTES) {
        await reader.cancel();
        throw new Error(`terminal peer addon archive exceeds the ${ARCHIVE_LIMIT_BYTES}-byte limit for ${asset.target}`);
      }
      chunks.push(value);
    }
  } catch (error) {
    await reader.cancel().catch(() => undefined);
    throw error;
  } finally {
    reader.releaseLock();
  }

  const archive = new Uint8Array(byteLength);
  let offset = 0;
  for (const chunk of chunks) {
    archive.set(chunk, offset);
    offset += chunk.byteLength;
  }
  return archive;
}

function verifyArchiveIntegrity(archive: Uint8Array, expectedIntegrity: string): void {
  const actualIntegrity = `sha512-${createHash("sha512").update(archive).digest("base64")}`;
  if (actualIntegrity !== expectedIntegrity) throw new Error("terminal peer addon archive integrity check failed");
}

function gunzipArchive(archive: Uint8Array): Uint8Array {
  try {
    return gunzipSync(archive, { maxOutputLength: TAR_LIMIT_BYTES });
  } catch (error) {
    throw new Error("terminal peer addon archive is not a bounded gzip tarball", { cause: error });
  }
}

function extractAddon(tar: Uint8Array, member: string): Uint8Array {
  let offset = 0;
  let addon: Uint8Array | null = null;
  let memberCount = 0;
  const entryNames = new Set<string>();
  while (offset < tar.byteLength) {
    if (tar.byteLength - offset < 512) throw new Error("terminal peer tarball has a truncated header");
    const header = tar.subarray(offset, offset + 512);
    if (header.every((byte) => byte === 0)) {
      if (!tar.subarray(offset).every((byte) => byte === 0)) throw new Error("terminal peer tarball has data after its end marker");
      if (memberCount !== 1 || !addon) throw new Error("terminal peer tarball did not contain exactly one addon member");
      return addon;
    }

    verifyTarChecksum(header);
    const type = header[156]!;
    const name = tarEntryPath(header);
    validateTarPath(name, type === 53);
    const entryName = name.endsWith("/") ? name.slice(0, -1) : name;
    if (entryNames.has(entryName)) throw new Error("terminal peer tarball contains duplicate entries");
    entryNames.add(entryName);
    if (type === 1 || type === 2) throw new Error("terminal peer tarball contains a link entry");
    if (type !== 0 && type !== 48 && type !== 53) throw new Error("terminal peer tarball contains an unsupported entry type");

    const size = tarOctal(header, 124, 12, "size");
    if (type === 53 && size !== 0) throw new Error("terminal peer tarball directory has content");
    const payloadStart = offset + 512;
    const payloadEnd = payloadStart + size;
    const paddedEnd = payloadStart + Math.ceil(size / 512) * 512;
    if (!Number.isSafeInteger(payloadEnd) || paddedEnd > tar.byteLength) {
      throw new Error("terminal peer tarball has a truncated entry");
    }

    if (name === member) {
      if (type !== 0 && type !== 48) throw new Error("terminal peer addon member is not a regular file");
      memberCount += 1;
      if (memberCount > 1) throw new Error("terminal peer tarball contains duplicate addon members");
      if (size === 0) throw new Error("terminal peer addon member is empty");
      addon = tar.slice(payloadStart, payloadEnd);
    }
    offset = paddedEnd;
  }
  throw new Error("terminal peer tarball has no end marker");
}

function tarEntryPath(header: Uint8Array): string {
  const name = tarText(header, 0, 100, "name");
  const prefix = tarText(header, 345, 155, "prefix");
  if (!name) throw new Error("terminal peer tarball entry has no name");
  return prefix ? `${prefix}/${name}` : name;
}

function validateTarPath(path: string, directory: boolean): void {
  const hasTrailingSlash = path.endsWith("/");
  const normalized = hasTrailingSlash ? path.slice(0, -1) : path;
  if (!normalized || (!directory && hasTrailingSlash) || path.includes("\\") || path.startsWith("/")) {
    throw new Error("terminal peer tarball contains an invalid path");
  }
  const segments = normalized.split("/");
  if (segments.some((segment) => !segment || segment === "." || segment === "..")) {
    throw new Error("terminal peer tarball contains a path traversal entry");
  }
}

function verifyTarChecksum(header: Uint8Array): void {
  const expected = tarOctal(header, 148, 8, "checksum");
  let actual = 0;
  for (let idx = 0; idx < header.byteLength; idx += 1) {
    actual += idx >= 148 && idx < 156 ? 32 : header[idx]!;
  }
  if (actual !== expected) throw new Error("terminal peer tarball header checksum failed");
}

function tarOctal(header: Uint8Array, start: number, length: number, field: string): number {
  let end = start + length;
  for (let idx = start; idx < start + length; idx += 1) {
    if (header[idx] === 0) {
      end = idx;
      for (let padding = idx + 1; padding < start + length; padding += 1) {
        if (header[padding] !== 0 && header[padding] !== 32) throw new Error(`terminal peer tarball has invalid ${field}`);
      }
      break;
    }
  }
  const digits = String.fromCharCode(...header.subarray(start, end)).trim();
  if (!/^[0-7]+$/.test(digits)) throw new Error(`terminal peer tarball has invalid ${field}`);
  const value = Number.parseInt(digits, 8);
  if (!Number.isSafeInteger(value)) throw new Error(`terminal peer tarball has oversized ${field}`);
  return value;
}

function tarText(header: Uint8Array, start: number, length: number, field: string): string {
  let end = start + length;
  for (let idx = start; idx < start + length; idx += 1) {
    if (header[idx] === 0) {
      end = idx;
      for (let padding = idx + 1; padding < start + length; padding += 1) {
        if (header[padding] !== 0) throw new Error(`terminal peer tarball has invalid ${field}`);
      }
      break;
    }
  }
  const bytes = header.subarray(start, end);
  if (bytes.some((byte) => byte < 32 || byte > 126)) throw new Error(`terminal peer tarball has invalid ${field}`);
  return String.fromCharCode(...bytes);
}

function loadTerminalPeerNativeManifest(): TerminalPeerNativeManifest {
  const packageJson = JSON.parse(readFileSync(new URL("../apps/worker/package.json", import.meta.url), "utf8")) as {
    dependencies?: Record<string, unknown>;
  } | null;
  const packageVersion = packageJson?.dependencies?.["node-datachannel"];
  if (typeof packageVersion !== "string" || !/^\d+\.\d+\.\d+$/.test(packageVersion)) {
    throw new Error("terminal peer native dependency must use an exact version");
  }
  const decoded = JSON.parse(readFileSync(new URL("./terminal-peer-native-assets.json", import.meta.url), "utf8")) as {
    version?: unknown;
    member?: unknown;
    targets?: unknown;
  };
  if (decoded.version !== 1 || decoded.member !== ADDON_MEMBER || !Array.isArray(decoded.targets)) {
    throw new Error("terminal peer native asset manifest is invalid");
  }

  const assets = new Map<TerminalPeerNativeTarget, TerminalPeerNativeAsset>();
  for (const rawEntry of decoded.targets) {
    if (rawEntry === null || typeof rawEntry !== "object" || Array.isArray(rawEntry)) {
      throw new Error("terminal peer native asset manifest has an invalid target entry");
    }
    const entry = manifestEntry(rawEntry as Record<string, unknown>);
    if (!isTerminalPeerNativeTarget(entry.target) || assets.has(entry.target)) {
      throw new Error("terminal peer native asset manifest has duplicate or unsupported targets");
    }
    const expectedSuffix = terminalPeerNativeSuffixByTarget[entry.target];
    const expectedPackage = `@node-datachannel/${entry.suffix}`;
    const expectedTarball = `https://registry.npmjs.org/${expectedPackage}/-/${entry.suffix}-${packageVersion}.tgz`;
    if (
      entry.suffix !== expectedSuffix || entry.package !== expectedPackage || entry.version !== packageVersion
      || entry.tarball !== expectedTarball || !/^sha512-[A-Za-z0-9+/]+={0,2}$/.test(entry.integrity)
    ) {
      throw new Error("terminal peer native asset manifest violates the pinned package contract");
    }
    assets.set(entry.target, { target: entry.target, tarball: entry.tarball, integrity: entry.integrity });
  }
  if (assets.size !== terminalPeerNativeTargetValues.length) {
    throw new Error("terminal peer native asset manifest does not cover every release target");
  }
  return { member: ADDON_MEMBER, assets };
}

function manifestEntry(value: Record<string, unknown>): ManifestEntry {
  return {
    target: manifestString(value, "target"),
    package: manifestString(value, "package"),
    version: manifestString(value, "version"),
    suffix: manifestString(value, "suffix"),
    tarball: manifestString(value, "tarball"),
    integrity: manifestString(value, "integrity"),
  };
}

function manifestString(value: Record<string, unknown>, key: string): string {
  const field = value[key];
  if (typeof field !== "string") throw new Error(`terminal peer native asset manifest has an invalid ${key}`);
  return field;
}

