// @ts-nocheck
// GENERATED by scripts/gen-embed.ts — do not edit.
// Empty stub: from-source loads the wasm and its digest sidecar from disk (import.meta.url).
export const WTERM_WASM_EMBED: string | null = null;
export const WTERM_WASM_SHA256_EMBED: string | null = null;
